### ISSUE TITLE
Program abnormal terminated

### ISSUE THREAD

**Issue by selene-neko** [DeadSix27/waifu2x-converter-cpp#10]
commit: f2cbb2e7d8d2be2f1083d7832914d68d8724bd9e
CPU: i7 6700K
error message:
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Freshly pulled from git and running on my Arch machine, and the program exit immediately.
Last build (few months ago, though) the issue wasn't exit.

**Comment by max20091** [comment]
It seems you don't have enough memory to run this program.
