### ISSUE TITLE
Crash when trying to use CUDA processor

### ISSUE THREAD

**Issue by MikuAuahDark** [DeadSix27/waifu2x-converter-cpp#100]
Somewhat similar to #35, but I used Windows binaries in release page ([v5.2.3](https://github.com/DeadSix27/waifu2x-converter-cpp/tree/v5.2.3) as of writing) and I don't actually building from source.

So, any attempt to use CUDA processor (which is default in my laptop), it just crash at first iteration. I used 2x scaling as example.

```
D:\Application\waifu2x-converter_x64_1130\new>waifu2x-converter-cpp -i a.png -m scale --scale_ratio 2 -o b.png
CUDA: GeForce 930MX
start scaling
#1 2x scaling...
start process block (0,0) ...
Iteration #1(3->32)...
(crash here)
```

Tanakamura fork works correctly without problems ~~except it blue screen when trying to waifu2x GIF files~~, but it's limited to 2x noise, which is why I try to use this version, as this version also linked in nagadomi/waifu2x repository. OpenCL also works correctly, but it somewhat slower than CUDA, at least in Tanakamura fork.

If you happen to have `w2xc.dll` and `waifu2x-converter-cpp.exe` with debug symbols for VS, I may able to get stack trace in Visual Studio 2017.

OS is Windows 10 1809, GPU is GT930MX, CPU is Intel Core i5-7200u.

**Comment by YukihoAA** [comment]
Hi @MikuAuahDark,

I tested in my laptop and it works fine to me.

We updated CUDA Toolkit to version 10, and CUDA Toolkit version 10 needs latest Graphic Driver.

Please check your driver version is grater then 411.31 and please install latest VGA driver in NVIDIA homepage :)


I tested in i5-6200U / GeForce 940MX / Windows 1803


By the way, otae is tenshi

**Comment by DeadSix27** [comment]
"otae is tenshi?"

**Comment by MikuAuahDark** [comment]
Can it support version 390.77? I'm hearing feedback that version 400 onwards degrade the performance while gaming, which is why I need to think twice before updating the driver, as 390.77 is the best driver for my laptop, even better than the one that's supplied by the laptop CD.

**Comment by YukihoAA** [comment]
You may build waifu2x-converter-cpp with CUDA 9 yourself but I cannot guarantee It works correctly (It may works but i never tested..)

OR you can use previous version of compiled binary.

Otae is character in BanG Dream! that is MikuAuahDark's Profile image.

**Comment by YukihoAA** [comment]
@MikuAuahDark 5.2 or lower may works to you.

**Comment by MikuAuahDark** [comment]
5.2 seems doesn't support CUDA as the release page information says.

**Comment by YukihoAA** [comment]
It supports, but in release page, may not build for CUDA... 

you may try Binary that i built for my Application

[waifu2x-Snowshell 1.6.4](https://github.com/YukihoAA/waifu2x_snowshell/releases/tag/v1.6.4)

**Comment by DeadSix27** [comment]
@YukihoAA I added min driver version to release page: <https://github.com/DeadSix27/waifu2x-converter-cpp/releases/tag/v5.2.3>

> :: Otae (Hanazono Tae) is character in BanG Dream! that is MikuAuahDark's Profile image.

weeb

**Comment by MikuAuahDark** [comment]
Thanks @YukihoAA, but I was looking for command-line solution.

I'll just stay with Tanakamura fork for longer until I can fully decide to update my graphics driver.

**Comment by YukihoAA** [comment]
@MikuAuahDark there is full binary inside of my zip, check waifu2x-convter folder

**Comment by MikuAuahDark** [comment]
I'll check it out later then.

**Comment by MikuAuahDark** [comment]
Okay I've checked your build (@YukihoAA) and the bundled waifu2x-converter seems work fine. Thank you, you can close this issue (since you re-opened it).

**Comment by YukihoAA** [comment]
@MikuAuahDark Ok, Have a nice day >_<

**Comment by YukihoAA** [comment]
@MikuAuahDark Ok, Have a nice day >_<
