### ISSUE TITLE
Versions newer than 5.2 crashing - "couldn't open noise0_model.json"

### ISSUE THREAD

**Issue by NintendoManiac64** [DeadSix27/waifu2x-converter-cpp#106]
Version 5.2.1 doesn't really provide any information in the command line output while v5.2.2 and newer provide the following error:

Error : couldn't open C:\Users\Ron\Desktop\v5.2.2\models\anime_style_art_rgb/noise0_model.json

I'm running Windows 7 SP1 x64 with a Pentium G3258 + Intel integrated graphics; version 5.2 worked perfectly.

**Comment by DeadSix27** [comment]
Make sure you download this version: <https://github.com/DeadSix27/waifu2x-converter-cpp/releases/tag/v5.2.3> and extract the entire package.

**Comment by NintendoManiac64** [comment]
That was the version I already tried to use - heck the "waifu2x-DeadSix27-vc15-cv401-win64_v523.7z" download link is even a different color as my browser history remembers that I've already previously clicked it.

**Comment by DeadSix27** [comment]
Try a different folder location to extract it to and make very sure you extracted all the files (use recent 7-zip version)

**Comment by NintendoManiac64** [comment]
Wait a minute, I just realized that v5.2 was the last version that actually included "waifu2x-gui.exe" and I had been re-using that in the newer versions (basically I had been extracting all files from the newer versions directly on top of all files of my pre-existing working v5.2 copy)

...but uh, that then begs the question - how am I supposed to even use versions newer than v5.2 if they don't include "waifu2x-gue.exe"?

**Comment by DeadSix27** [comment]
By not using the GUI, or stick with older version.
Have you been using this one? <https://github.com/YukihoAA/waifu2x_snowshell/releases>

**Comment by NintendoManiac64** [comment]
It does seem like Snowshell works, thank you for the help.

Unfotunately it doesn't seem to properly handle opening images directly into the program (like via right clicking an image, then going to "Open with...") as it dumps the program config file and such into the directory of the image in question, but this would be something to for the Snowshell github issue tracker rather than here.

**Comment by YukihoAA** [comment]
Snowshell is not for right click conversion and it only designed for drag-and-drop conversion.

right click conversion feather is supported by this project, please use sendTo Script.

https://github.com/DeadSix27/waifu2x-converter-cpp/blob/master/BUILDING.md

**Comment by YukihoAA** [comment]
and.. Snowshell includes latest snapshot in this repository (I include binaries just after push my works to waifu2x-converter-master branch)

**Comment by YukihoAA** [comment]
and i cannot find waifu2x-gui.exe in 5.2 version... may be developed by different project?
![image](https://user-images.githubusercontent.com/20253131/53803282-938ae900-3f87-11e9-8c89-0cb66a37b7b6.png)

**Comment by YukihoAA** [comment]
yee I found waifu2x-gui's repo : https://github.com/maz-1/waifu2x-gui

please contect in that repository.

**Comment by YukihoAA** [comment]
This issue is not belongs to waifu2x-converter-cpp project so I'wll close this issue.

for further infomation, please contect maz-1's waifu2x-gui repo
: https://github.com/maz-1/waifu2x-gui

**Comment by LtqxWYEG** [comment]
I get the error Error : couldn't open models_rgb/noise0_model.json when I use the newest release, clean, just the files in the release zip. Yes, the command line program.

**Comment by DeadSix27** [comment]
Linux? Build with -DINSTALL_MODELS=ON ? 
Even if yes, search your entire machine for old instances of w2x binary (main program),delete it, rebuild it with INSTALL_MODELS and try again.

**Comment by LtqxWYEG** [comment]
No, Windows 10. After first time download. Sorry forgot to say.
I used the program/gui offered by the official waifu2x github instead. That works great.

**Comment by YukihoAA** [comment]
@LtqxWYEG This project not works as Official waifu2x repo. it works differently. ask gui project creator to how to fix it or use waifu2x-cpp-converter by cmd prompt.

**Comment by LtqxWYEG** [comment]
I meant that it is or was a problem with your program, but that I am using the software from the official github instead and that worked fine. Your program did not work on my PC. I am getting the error stated above when using your program.

**Comment by YukihoAA** [comment]
@LtqxWYEG OK I got it, then this should be created in new issue.
Please create new issue and report your detail information with error message screenshot.
