### ISSUE TITLE
Specifying input folder with "--input" does not work, but "-i" works

### ISSUE THREAD

**Issue by K4YT3X** [DeadSix27/waifu2x-converter-cpp#109]
I'm working an automation script that upscales videos using this library, and I ran into a bit of a problem when trying to process all images in a folder. While using `-i some/directory` works, `--input some/directory` gives `cv::imread("some path") failed`.

Here are some screenshots that should make this more intuitive. All arguments are listed in the "DBG" line.

### `-i`
![image](https://user-images.githubusercontent.com/21986859/54074499-fe2a7600-4260-11e9-8e25-487361ef7835.png)

### `--input`
![image](https://user-images.githubusercontent.com/21986859/54074502-01256680-4261-11e9-97f4-cd97d75a1eeb.png)

I first thought maybe these two arguments have different meanings, but it's said that they mean the same thing in the help page.

![image](https://user-images.githubusercontent.com/21986859/54074522-55c8e180-4261-11e9-9b97-5cb59dcb2f08.png)

**Comment by DeadSix27** [comment]
@K4YT3X See if this build fixes it for you please: https://share.toji.site/w2x_input_fix.7z

**Comment by K4YT3X** [comment]
@DeadSix27 yes the problem is gone.
Much appreciated for the rapid response.

**Comment by DeadSix27** [comment]
Fixed via https://github.com/DeadSix27/waifu2x-converter-cpp/commit/d354c068b845189f957e246569c0f93c52c1008f
