### ISSUE TITLE
(Question) Compile as Library

### ISSUE THREAD

**Issue by blitzcaster** [DeadSix27/waifu2x-converter-cpp#11]
Is it possible to compile this software as a library? If so, any suggestion on how to do it? I'm trying to create an Android version of waifu2x using OpenCL on smartphone. If using this software as library is possible it going to save a lot of work. Thanks in advance.

**Comment by DeadSix27** [comment]
Does it not automatically compile w2xc.lib ? I do not have the build files installed currently.

If you link to w2xc.lib and include w2xconv.h, you can use it as a library, afaik.

**Comment by blitzcaster** [comment]
Thx for your help, I get it compile and running on Android. Currently running using ARM NEON, still trying to get it run on OpenCL. This is my first time using CMake and Android NDK, still need some getting use to. When it's done I'm planning to release it on Play Store and open source it. Thx again.

**Comment by DeadSix27** [comment]
@blitzcaster Mention the URL here if its done so I can hotlink to it in the readme

**Comment by DeadSix27** [comment]
@blitzcaster I'll close this for now, just reply if you still need help.
