### ISSUE TITLE
Question: Release file decompression error with PyLZMA in Python script

### ISSUE THREAD

**Issue by K4YT3X** [DeadSix27/waifu2x-converter-cpp#113]
I was trying to make my automation script decompressing the `waifu2x-DeadSix27-vc15-cv401-win64_v523.7z` file with pylzma and py7zlib for automatic setup, but it throws me a ValueError when I was trying to decompress `conv.exe`. It looks something like this:

```
>>> z.getmember('conv.exe').read()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\K4YT3X\AppData\Local\Programs\Python\Python37\lib\site-packages\py7zlib.py", line 632, in read
    data = getattr(self, decoder)(coder, data, level, num_coders)
  File "C:\Users\K4YT3X\AppData\Local\Programs\Python\Python37\lib\site-packages\py7zlib.py", line 702, in _read_lzma
    return self._read_from_decompressor(coder, dec, input, level, num_coders, with_cache=True)
  File "C:\Users\K4YT3X\AppData\Local\Programs\Python\Python37\lib\site-packages\py7zlib.py", line 686, in _read_from_decompressor
    data = decompressor.decompress(input, self._start+size)
ValueError: data error during decompression
>>>
```

I know this is not waifu2x-converter-cpp's problem, but packaging the released files in a 7z seems to be really difficult for scripts like python to decompress. In comparison, the released zip files from waifu2x-caffe works pretty well with Python's `zipfile` library.

Is there a particular reason why 7z is used? Is it possible to also release in zip format in the future?

Thank you.

**Comment by DeadSix27** [comment]
Can't you just run p7zip from a subprocess?
7z compresses like 30% more than gzip (a not insignificant amount), hence me using it.

**Comment by K4YT3X** [comment]
My script is designed for Windwos platform only at the moment, and in any case, that will require the client machine to have 7zip installed, which is yet an extra step.

I'll try libarchive and see if that solves the problem. That library looks nice so far.

**Comment by DeadSix27** [comment]
zip @ max: ~37mb
7u @ max: ~27mb


I'd also argue that most users have that installed anyway, especially the target audience of this program.

**Comment by K4YT3X** [comment]
> EDIT: Sorry, didn't mean to close

No worries, and in any other ways, I understand this is not really a bug or defect on waifu2x-converter-cpp's side. It's more of a problem that I'm facing by automating the deployment of this repository.

> I'd also argue that most users have that installed anyway, especially the target audience of this program.

For those that use this program directly, I agree. However, for secondary developments like my automated script, I see a lot of people not knowing the basics of command line. Also, the sole reason of an automated script is to ease the hassle of the users figuring everything out themselves.

I just looked into `libarchive`, and it does indeed decompress 7z conveniently enough. However, according to this following issue, it requires manual steps to compile and setup on Windows, so it's therefore even more of a problem than `pylzma`.

At this point, I would say that 7z really doesn't do well with Python on Windows. Indeed, 7zip provides better compression ratio, which is easier for higher-level users to download due to its smaller size, but as for the high-level applications that want to use this program as a component, 7z might cause integration problems.

As I mentioned before, it's purely up to you on how and in what format to publish the files, but I just want to at least make you aware that some might have problems with 7z. I will suggest zip format to be included in future releases, so people with different needs take what they need.

Also, thank you for writing this program. It has been really useful for both me and downstream users of mine.

**Comment by DeadSix27** [comment]
I use zip now.

**Comment by K4YT3X** [comment]
> I use zip now.

Much appreciated. I was able to continue with my development, and now this program can be deployed automatically.
