### ISSUE TITLE
Output image format (jpg, etc.)

### ISSUE THREAD

**Issue by K4YT3X** [DeadSix27/waifu2x-converter-cpp#114]
Some users of my script reported that **when upscaling a large sum of images, saving frames in JPEG format saves a lot of storage space as compared to PNG**.

In `waifu2x-caffe`, you can specify output image format using the `-e` option, but I didn't see something similar in `waifu2x-converter-cpp`'s help page.

Would you be interested adding support for other output image formats?

**Comment by DeadSix27** [comment]
JPEG is a lossy and compressed format. hence the size difference, PNG is lossless and the better alternative for storage purposes.
But yeah, just use -o and change the extension

`w2x.exe -i inputfile.png -o outputfile.jpg` will save as jpg

**Comment by K4YT3X** [comment]
I know that it's lossy, but I just wanted to see how big the difference is.
Forget about this issue for now and here's why:

I did some tests with PNG and JPEG, and here are the results with waifu2x-caffe:

### PNG

![extracted_34](https://user-images.githubusercontent.com/21986859/54638283-11a7bf00-4a61-11e9-90cc-62193f4eda94.png)

### JPEG

![extracted_34](https://user-images.githubusercontent.com/21986859/54638282-11a7bf00-4a61-11e9-8243-8ae29037b20c.jpg)

The quality loss is way beyond what I was expecting, so please forget about this issuse.

**Comment by DeadSix27** [comment]
Doesn't look that bad on my end lol.

**Comment by DeadSix27** [comment]
Maybe need to add a jpeg quality option.

**Comment by K4YT3X** [comment]
> Maybe need to add a jpeg quality option.

 I do, for FFMPEG. Though at this point I'm questioning whether it's worth it to even try to get JPEG to work, since the whole point of waifu2x is to get sharper image and etc.

**Comment by K4YT3X** [comment]
> `w2x.exe -i inputfile.png -o outputfile.jpg` will save as jpg

On this topic though, my focus is on the situation where the input is a folder. I tried it earlier on, but if input is JPG, output seems to still be PNG.

**Comment by Sunseille** [comment]
convert the output file in jpg with ffmpeg?

**Comment by K4YT3X** [comment]
> convert the output file in jpg with ffmpeg?

then it will lose the point of saving disk space

**Comment by DeadSix27** [comment]
Fixed via #116, once its merged and reviewed

**Comment by K4YT3X** [comment]
@DeadSix27 wow nice. Thanks.
