### ISSUE TITLE
Arguments: Allow specifying output name same as input name when processing directory

### ISSUE THREAD

**Issue by brunoais** [DeadSix27/waifu2x-converter-cpp#118]
**Currently:**
Currently, when files are processed and a directory is given for input and output, the naming format is forcefully automatic ([main.cpp#L249](https://github.com/DeadSix27/waifu2x-converter-cpp/blob/b4566c0fb33e716cb092cbf6a557137b53acbfac/src/main.cpp#L249))

**My use-case:**
For my use-case, it is much more useful to get the output files in a different directory with the exact same names as the original ones with the intention to overwrite the original ones with the "waifu2x improved" ones after extensive compression.

**Request:**
May an argument be created, for example `--output-format={auto|original}`, so the extra information (noise level and resize size) that is currently added to the file name is not added at all?

**Comment by aka-katto** [comment]
Bumping interest - would be very useful for Dandere2x.
