### ISSUE TITLE
can you(any one) help me  solve this question?

### ISSUE THREAD

**Issue by OgreShader** [DeadSix27/waifu2x-converter-cpp#12]
I tried to complict  waifu2x-converter-cpp-master ,but has a peoblem.

2>w2xcr.obj : error LNK2019: unresolved external symbol __imp_w2xconv_convert_file referenced in function proc_thread
2>*****\Release\w2xcr.exe : fatal error LNK1120: 1 unresolved externals

I want to know  the reason to cause this result.

**Comment by YukihoAA** [comment]
I just created new [pull request#13](https://github.com/DeadSix27/waifu2x-converter-cpp/pull/13) about cmake script.

Just re-make your projects with my new cmake script. It will be work for you.

**Comment by DeadSix27** [comment]
@OgreShader Please report back if @YukihoAA 's PR fixed it.

**Comment by OgreShader** [comment]
@YukihoAA ,@DeadSix27     
Thank you !  I fixed it  with  YukihoAA 's  solution.

**Comment by DeadSix27** [comment]
@OgreShader :) good to know, thanks @YukihoAA
