### ISSUE TITLE
Program Quits Without Error Messages

### ISSUE THREAD

**Issue by K4YT3X** [DeadSix27/waifu2x-converter-cpp#121]
I was trying the new release out and processing images in a folder, but the program just exited without any messages (return code: `3221225477`).

![image](https://user-images.githubusercontent.com/21986859/55029890-95bdf180-4fe1-11e9-8f08-a9c7ed5f89d8.png)

**Comment by K4YT3X** [comment]
![image](https://user-images.githubusercontent.com/21986859/55030081-f64d2e80-4fe1-11e9-9ab7-8ac53a0d3e08.png)

**Comment by DeadSix27** [comment]
Sounds like an issue with cuda or this build in particular not the code. The main difference is that I built that one with CUDA 10.1 and the other with 10.0, try newest nvidia drivers. I'll test more tomorrow. If you can try building it yourself

**Comment by K4YT3X** [comment]
@DeadSix27 thank you, will do.

**Comment by DeadSix27** [comment]
Test both builds:

https://github.com/DeadSix27/various_stuff/releases/download/0.0/w2x_Test-A.7z
https://github.com/DeadSix27/various_stuff/releases/download/0.0/w2x_Test-B.7z

**Comment by K4YT3X** [comment]
@DeadSix27 both test builds work just fine.
It's only https://github.com/DeadSix27/waifu2x-converter-cpp/releases/tag/v5.2.4 that's not working.

**Comment by K4YT3X** [comment]
@DeadSix27 OpenCL works just fine.

![image](https://user-images.githubusercontent.com/21986859/55116490-ca9f7680-50bd-11e9-858f-5befd42c11af.png)

**Comment by DeadSix27** [comment]
Can you test:

https://github.com/DeadSix27/various_stuff/releases/download/0.0/test_C.7z
https://github.com/DeadSix27/various_stuff/releases/download/0.0/test_d.7z
https://github.com/DeadSix27/various_stuff/releases/download/0.0/test_e.7z

**Comment by K4YT3X** [comment]
> Can you test:
> 
> https://github.com/DeadSix27/various_stuff/releases/download/0.0/test_C.7z
> https://github.com/DeadSix27/various_stuff/releases/download/0.0/test_d.7z
> https://github.com/DeadSix27/various_stuff/releases/download/0.0/test_e.7z

![image](https://user-images.githubusercontent.com/21986859/55117198-51555300-50c0-11e9-9303-cc337bbdfeec.png)

Gimme 30 minutes.

**Comment by K4YT3X** [comment]
Sorry for the late reply. I'm really busy at the time.
All 3 of them failed.

**Comment by DeadSix27** [comment]
One last time, test them all, i omitted the models and cv dll and made it separate zip to make this faster:

models, dll: https://github.com/DeadSix27/various_stuff/releases/download/0.0/test_models_and_cv.7z

https://github.com/DeadSix27/various_stuff/releases/download/0.0/test_1.7z
https://github.com/DeadSix27/various_stuff/releases/download/0.0/test_2.7z
https://github.com/DeadSix27/various_stuff/releases/download/0.0/test_3.7z
https://github.com/DeadSix27/various_stuff/releases/download/0.0/test_4.7z
https://github.com/DeadSix27/various_stuff/releases/download/0.0/test_5.7z
https://github.com/DeadSix27/various_stuff/releases/download/0.0/test_6.7z

Have fun

**Comment by K4YT3X** [comment]
Finally found time to do this.

|#|Result|
|-|-|
|1|☓|
|2|☓|
|3|√|
|4|☓|
|5|√|
|6|☓|

**Comment by DeadSix27** [comment]
Cuda issue, did you check if drivers are correctly installed? Try on a blank system.

**Comment by K4YT3X** [comment]
My system is running on ESXi, and for some reason I can't install Nvidia driver updates.
I'll try to figure something out.

**Comment by K4YT3X** [comment]
@DeadSix27 I updated my Nvidia driver, and everything seems to be fine now.

**Comment by DeadSix27** [comment]
Added version requirement to version info: https://github.com/DeadSix27/waifu2x-converter-cpp/releases/tag/v5.2.4

**Comment by K4YT3X** [comment]
![LINE_Menhera_chan6](https://user-images.githubusercontent.com/21986859/55282713-87910d80-5320-11e9-9212-dd8e207dee70.png)
