### ISSUE TITLE
Fails saving very tall/wide with WebP (works fine with other formats)

### ISSUE THREAD

**Issue by Kattus** [DeadSix27/waifu2x-converter-cpp#128]
As the title suggests, when specifying output format as webp and the input in something like 2000x10000 (a comic for example), or 10000x2000 it will result in the following error:
```
imwrite_('/home/katt/white_[NS-L1][x2.000000].webp'): can't write data: OpenCV(4.1.0) /build/opencv/src/opencv-4.1.0/modules/imgcodecs/src/grfmt_webp.cpp:304: error: (-215:Assertion failed) size > 0 in function 'write'

cv::imwrite("/home/katt/white_[NS-L1][x2.000000].webp") failed
process successfully done! (all:25.4138[sec], 1 [files processed], 1 [files errored], 2423.78[GFLOPS], filter:21.3472[sec], 2885.51[GFLOPS])
```

other formats such as png and jpg works just fine.

**Comment by DeadSix27** [comment]
Seems like a bug in opencv in that it doesn't tell us what happend:

If one looks at https://github.com/opencv/opencv/blob/master/modules/imgcodecs/src/grfmt_webp.cpp#L304

We can see that WebPEncode* should return the size and according to the API docs:
https://developers.google.com/speed/webp/docs/api#simple_encoding_api
It will return 0 in case it fails

However to see why it fails I assume we have to ask webp about the error
By using this struct:
https://github.com/webmproject/libwebp/blob/master/src/webp/encode.h#L278

And request it by: 
https://github.com/webmproject/libwebp/blob/master/src/webp/encode.h#L535

However I don't see any code related to that in opencv:
https://github.com/opencv/opencv/blob/master/modules/imgcodecs/src/grfmt_webp.cpp#L235


So Idk..

About your issue, you can guess which one it may be, as we don't know without modifying OpenCV:
```
  VP8_ENC_ERROR_OUT_OF_MEMORY,            // memory error allocating objects
  VP8_ENC_ERROR_BITSTREAM_OUT_OF_MEMORY,  // memory error while flushing bits
  VP8_ENC_ERROR_NULL_PARAMETER,           // a pointer parameter is NULL
  VP8_ENC_ERROR_INVALID_CONFIGURATION,    // configuration is invalid
  VP8_ENC_ERROR_BAD_DIMENSION,            // picture has invalid width/height
  VP8_ENC_ERROR_PARTITION0_OVERFLOW,      // partition is bigger than 512k
  VP8_ENC_ERROR_PARTITION_OVERFLOW,       // partition is bigger than 16M
  VP8_ENC_ERROR_BAD_WRITE,                // error while flushing bytes
  VP8_ENC_ERROR_FILE_TOO_BIG,             // file is bigger than 4G
  VP8_ENC_ERROR_USER_ABORT,               // abort request by user
```

Maybe there is a way to see the error from CV.. but I can't find it.

**Comment by Kattus** [comment]
Nevermind, I realised what is wrong when also imagemagick failed converting from png to webp..

`The maximum pixel dimensions of a WebP image is 16383 x 16383.`
https://developers.google.com/speed/webp/faq#what_is_the_maximum_size_a_webp_image_can_be

So that's that.

**Comment by DeadSix27** [comment]
Oh right, your input image was below but the scaled out wasn't..

**Comment by DeadSix27** [comment]
Kinda is still an issue in opencv tbh
