### ISSUE TITLE
Linux Build?

### ISSUE THREAD

**Issue by k4yt3x** [DeadSix27/waifu2x-converter-cpp#129]
I was just looking into the possibilities of making my project Linux-compatible, and someone in my repo posted this build of waifu2x-converter-cpp's for Linux. Just want to ask how hard it is to make an official build for Linux.

https://github.com/tanakamura/waifu2x-converter-cpp/issues/4

If it's too much work for you to make a build, I can try to make a package for Debian.

All the best,
K

**Comment by YukihoAA** [comment]
Actually We always supports linux.

check [BUILDING.md](https://github.com/DeadSix27/waifu2x-converter-cpp/blob/master/BUILDING.md)

You can BUILD your own build by following instructions.

**Comment by k4yt3x** [comment]
@YukihoAA thanks and sorry for asking.
Totally missed that entire section on README out of my own stupidity.
