### ISSUE TITLE
Error when converting directory on OSX, .DS_Store causes runtime error

### ISSUE THREAD

**Issue by velara3** [DeadSix27/waifu2x-converter-cpp#131]
When defining a directory I'm getting an error:

**Command:** 

    waifu2x-converter-cpp --model-dir /Users/user/Documents/waifu2x-converter-cpp/models --scale- 
    ratio 2 -i /Users/user/Documents/testfolder -o /Users/user/Documents/testoutput

**Error:** 
>We're going to be operating in a directory. dir:"/Users/user/Documents/testfolder"
>libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: basic_string
>Abort trap: 6

**Comment by YukihoAA** [comment]
Please capture the version string by using

`waifu2x-converter-cpp --version`

**Comment by YukihoAA** [comment]
![image](https://user-images.githubusercontent.com/20253131/57012656-99790f80-6c42-11e9-8afd-af685556cc7a.png)

It works fine with me in version 

v5.2.4 (master-b4566c0)
v5.2.4 (master-a268359)

**Comment by velara3** [comment]
waifu2x-converter-cpp --version

> waifu2x-converter-cpp  version: v5.2.4 (master-1eea2b3)

**Comment by YukihoAA** [comment]
I edited some codes can affect to this issue. please re-compile project with latest codes (It should be master-a268359)

**Comment by YukihoAA** [comment]
sorry I was created many PR's and there is some commits that i forgot to push. I will make new PR in a hour and please try that version. I will add comment when codes are ready

**Comment by YukihoAA** [comment]
please try in osx_dir_support branch.

'git checkout osx_dir_support'

checkout to osx_dir_support branch then try to build again in normal way.

version string should be v5.2.4 (osx_dir_support-7e6a1ea)

**Comment by velara3** [comment]
I ran: `./waifu2x-converter-cpp --version`

./waifu2x-converter-cpp  version: v5.2.4 (osx_dir_support-7e6a1ea)'.

Then I run `/Users/user/Documents/waifu2x-converter-cpp/waifu2x-converter-cpp --jobs 2 --scale-ratio 2 --mode noise-scale --noise-level 3 -c 0 -f png --input '/Users/user/Documents/test/' --output /Users/user/Documents/test/test2/`

And getting the same error:
CPU: Intel(R)...
We're going to be operating in a directory. dir:"/Users/user/Documents/test/"
libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: basic_string
Abort trap: 6

Is it possible to switch to checkout an earlier release and that would fix the issue?

**Comment by YukihoAA** [comment]
do you have a previous version that works fine with OSX? if you have, please let us know which version that works.

you can download previous codes at release page.

**Comment by velara3** [comment]
I switched to 5.4.2 and when running cmake again it had this message:

>-- Found git, set version to: v5.2.4 (HEAD-b4566c0)
>-- System is: Darwin (Apple)
>CUDA_TOOLKIT_ROOT_DIR not found or specified
>-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE >CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) 
>-- CUDA not found. disabled.
>-- Configuring done
>-- Generating done

I then built using `> make -j4` and ran previous command as before. The output was better but stumbled on DS_Store.  

>CPU: Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
>We're going to be operating in a directory. dir:"/Users/user/Documents/test"
>[1/3] ".DS_Store"
>Floating point exception: 8

I'll check other versions.

**Comment by YukihoAA** [comment]
@velara3 when you don't use CUDA, you can ignore warnings about CUDA. it's ok.

**Comment by velara3** [comment]
FYI I rechecked out `osx_directory_support` and `master` and it is also works now. 

It looks like the original error is caused by the `.DS_Store` being in the directory. If I remove that file all versions appear to work correctly. FYI .DS_Store is hidden by default on OSX.

**Comment by YukihoAA** [comment]
when i create .DS_Store in windows, it does not make error. (so i cannot reproduce this situation)

may be it is related to permission or something??

**Comment by YukihoAA** [comment]
in branch `integrated_unicode_support` could fix this problem (crashing due to .DS_Store)

**Comment by velara3** [comment]
OK I see help wanted tag. I'll help test it.

    $ ./waifu2x-converter-cpp --version

>./waifu2x-converter-cpp  version: v5.2.4 (integrated_unicode_support-3638728)

Same error: 

>libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: basic_string
>Abort trap: 6

When delete of .DS_Store directory conversion is successful, when .DS_Store exists error.

**Comment by YukihoAA** [comment]
could you please testing in branch integrated_unicode_support, d4b5a2f

I added some check function to catch file not supported.

**Comment by velara3** [comment]
waifu2x-converter-cpp --version

>./waifu2x-converter-cpp  version: v5.2.4 (integrated_unicode_support-d4b5a2f) 

It is working in my tests and shows this message: 

>We're going to be operating in a directory. dir:"/Users/test/Documents/test"
>Skipping file '.DS_Store' for having an unsupported file extension ()
>[1/2] "test.jpg"

**Comment by YukihoAA** [comment]
OK! It is what it should be.

Thank you for your help!

**Comment by velara3** [comment]
> @velara3 when you don't use CUDA, you can ignore warnings about CUDA. it's ok.

What does it mean? I am using CPU on my computer but want to use it on another computer that has a GPU and I am making a binary for it. Will ignoring this message cause issues on another computer?
