### ISSUE TITLE
Build fail with OpenCL lib check

### ISSUE THREAD

**Issue by YukihoAA** [DeadSix27/waifu2x-converter-cpp#133]
![image](https://user-images.githubusercontent.com/20253131/57118616-73b54d00-6d9f-11e9-97c7-9c8d4b849b3f.png)

I cannot build project in my new clean installed ubuntu 18.04 on aws.

i installed beignet-opencl-icd and opencl-headers by apt-get.

**Comment by DeadSix27** [comment]
maybe `ocl-icd-opencl-dev`?

**Comment by DeadSix27** [comment]
If that doesn't work can you create

`CMakeLists.txt`
```cmake
cmake_minimum_required(VERSION 3.13)
find_package(OpenCL REQUIRED)
message(WARNING "${OpenCL_INCLUDE_DIR}")
```
in empty folder, cd into it and run "cmake ."

then see if it detects it fine ?

![image](https://user-images.githubusercontent.com/1492505/57118886-70ea3600-6d66-11e9-8bb4-22fa69bd0ef2.png)

**Comment by YukihoAA** [comment]
'ocl-icd-opencl-dev' works for me. thanks
