### ISSUE TITLE
w2xcr does not supports unicode

### ISSUE THREAD

**Issue by Veshurik** [DeadSix27/waifu2x-converter-cpp#138]
If I drag image on any .exe file, nothing happens.
Well, almost all programs crashes.

Virtual Windows 7 machine.

w2xcr appears with blank window.
![1](https://user-images.githubusercontent.com/26744056/57180808-05eb4d00-6e95-11e9-90c9-c30a1dc8550b.JPG)

**Comment by DeadSix27** [comment]
CUDA/CL in VMs requires a passed through gpu.

Try running via CLI only and select the cpu instead of the gpu, find IDs by using "-l"

**Comment by Kattus** [comment]
> CUDA/CL in VMs requires a passed through gpu.

Shouldn't it fallback to CPU then though?

**Comment by DeadSix27** [comment]
Not if you have the CL or cuda packages installed, it detects those on my VM and just crashes when trying to use it.

**Comment by YukihoAA** [comment]
you cannot use by drag-and-drop images this program.

as this project is CLI Application, you need to use this by using cmd.exe

please check readme.md to use properly.

**Comment by DeadSix27** [comment]
The w2xcr + non unicode might actually be the issue here I guess, since he seems to be using russian Language.
