### ISSUE TITLE
Possible to show more details of error message

### ISSUE THREAD

**Issue by velara3** [DeadSix27/waifu2x-converter-cpp#139]
I used the following command: 
    waifu2x-converter-cpp --jobs 1 --scale-ratio 2 --mode noise-scale --noise-level 3 -f png --input /Users/user/Document/test --output /Users/user/Desktop/test

And the result is: 

>CPU: ...
cv::imread("/Users/user/Desktop/test") failed
process successfully done! (all:0.153821[sec], 1 [files processed], 1 [files errored], 0[GFLOPS], filter:0[sec], nan[GFLOPS])

Is it possible to show more details in the error message?

**Comment by DeadSix27** [comment]
Yes, Can you explain though what /test is, a file, a directory? an Empty directory?

W2x handles some errors wrong anyway or has no error handling at all.

**Comment by YukihoAA** [comment]
Ok it seems solved so i'll close this issue for you.

**Comment by DeadSix27** [comment]
Was gonna keep it open until I make a PR adding a bit more useful error logs, but its fine.
