### ISSUE TITLE
Improve log when scaling and filtering starts

### ISSUE THREAD

**Issue by DeadSix27** [DeadSix27/waifu2x-converter-cpp#144]
Currently the log begins with `start process block (1/3,1/4) ...`
until it reaches:

`start scaling`
`#1 2x scaling...`

It should also announce that it started filtering.. maybe steps-based?

We also have to keep scale-factor in mind, as that makes it do multiple scaling steps.

E.g example new output:

`Step 1/3, Filtering:`
`Step 2/3, Scaling 2x`
`Step 2/3, Scaling 2x #2`

**Comment by YukihoAA** [comment]
if we can hide 

start process block (2/4, 3/4) ...
```
#Iteration 1 ----
...
...
#Iteration 8 ------ 
```
total : 0.074[sec], 1566.123[GFLOPS]

and just shows up in option. (--essential-logs or --debug or something)

start process block (2/4, 3/4) ...
total : 0.074[sec], 1566.123[GFLOPS]

it will be helpful to see progress especially when we convert huge size of image.

**Comment by DeadSix27** [comment]
Maybe in that case we should make a new option:

--log-level 1 to 3

1 = equal to --silent
2 = only show process block()...
3 = show everything (same as without --silent)

And default to 2.

?

**Comment by YukihoAA** [comment]
@DeadSix27 It will be good!

**Comment by YukihoAA** [comment]
as we now have slicer, i suggest new log-level

5: Iteration...
4: process block (colum-row)
3: process-slices [n/m]
2: step 2/3 denoising...
1: same as silent
0: real silent
