### ISSUE TITLE
Fall back when image too large for webp

### ISSUE THREAD

**Issue by Kattus** [DeadSix27/waifu2x-converter-cpp#149]
Instead of failing to write file, fall back to png so the time and effort havent been wasted.

Pls no more of this :(
```
imwrite_('/home/katt/file_[NS-L1][x2.000000].webp'): can't write data: OpenCV(4.1.0) /build/opencv/src/opencv-4.1.0/modules/imgcodecs/src/grfmt_webp.cpp:304: error: (-215:Assertion failed) size > 0 in function 'write'

cv::imwrite("/home/katt/file_[NS-L1][x2.000000].webp") failed
Done, took: 99.485s total, file: 99.485s avg: 99.485s
Finished processing 1 files
Took: 100.141secs total, filter: 81.263secs; 0 files skipped, 1 files errored. [GFLOPS: 2677.08, GFLOPS-Filter: 3299.00]
```

**Comment by DeadSix27** [comment]
You should've added that the reason for this is that WebP only supports images up to 16383 x 16383.

From their FAQ:

> **What is the maximum size a WebP image can be?**

> WebP is bitstream-compatible with VP8 and uses 14 bits for width and height. The maximum pixel dimensions of a WebP image is 16383 x 16383.

**Comment by YukihoAA** [comment]
oh WebP max is 16383? then we need some check function for it..

**Comment by DeadSix27** [comment]
Yep, and we should not fall back, but instead error out, the user asked for WebP not PNG.

**Comment by Kattus** [comment]
Then please add it as an option to fallback? I'd much rather have a PNG file than no file at all.

**Comment by YukihoAA** [comment]
we can add error message and abort before conversion. not after operating it.

**Comment by DeadSix27** [comment]
That is what i meant yes.

**Comment by Kattus** [comment]
Still annoying for batch jobs of say 300 images as the end output is quite useless for figuring out which files errored out.

**Comment by YukihoAA** [comment]
Actually I don't understand why images needs to be bigger then 16383x16383.. image file size is more than 300MB each and it will require tons of times to run.. and run it in batch..???????? it will takes days!
