### ISSUE TITLE
Do you (any one) have a  Developing documents about waifu2x ?

### ISSUE THREAD

**Issue by OgreShader** [DeadSix27/waifu2x-converter-cpp#15]
I have some questions about  waifu2x  by read  the  code  .  
       For example , What is nInputPlanes and nOutputPlanes   in   the  class Model ? 
       So ,do you  have a  Developing documents  about it ?
       I need it to Konw the class's   function and members's  description.

**Comment by iame6162013** [comment]
Are you asking about the webpage in: docs/internals/waifu2x.html ?

**Comment by DeadSix27** [comment]
Everything I know is in the source code.
You could ask @nagadomi maybe he knows a bit more?
