### ISSUE TITLE
CUDA_TOOLKIT_ROOT_DIR not found or specified

### ISSUE THREAD

**Issue by velara3** [DeadSix27/waifu2x-converter-cpp#159]
When I run cmake it has this message:

-- Found git, set version to: v5.2.4 (HEAD-b4566c0)
-- System is: Darwin (Apple)
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE >CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY)
-- CUDA not found. disabled.
-- Configuring done
-- Generating done

Is there something I'm missing? I'm following the Mac build steps here.
https://github.com/DeadSix27/waifu2x-converter-cpp/blob/master/BUILDING.md

**Comment by DeadSix27** [comment]
Try specifying ` -DCUDA_TOOLKIT_ROOT_DIR=(path)`

Not sure where on MacOS that is though...

You'll have to find it.

**Comment by DeadSix27** [comment]
I assume you got this working?

**Comment by velara3** [comment]
I've downloaded the NVIDIA drivers dmg (2.2GB) and installed it. I haven't had a chance to do much else yet.

**Comment by DeadSix27** [comment]
Hmm.. maybe the issue is actually on the cmake script.. i could have overlooked APPLE.. one second.

**Comment by DeadSix27** [comment]
nvm, i think its fine but, you can test this patch:

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 0b7f8b9..f45f4d0 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -101,7 +101,12 @@ set(HAVE_OPENCV FALSE)
 set(HAVE_OPENCV_3_X FALSE)
 if (ENABLE_OPENCV)
 	if(UNIX)
-		set(OPENCV_PREFIX "/usr" CACHE FILEPATH "OpenCV path")
+		if (DEFINED OPENCV_PREFIX)
+			set(OpenCV_DIR "${OPENCV_PREFIX}" CACHE FILEPATH "OpenCV 4.x path")
+		else()
+			set(OPENCV_PREFIX "/usr" CACHE FILEPATH "OpenCV path")
+			set(OpenCV_DIR "${OPENCV_PREFIX}" CACHE FILEPATH "OpenCV 4.x path")
+		endif()
 		find_package(OpenCV)
 		if(NOT OPENCV_FOUND)
 			find_package(PkgConfig REQUIRED)

```

**Comment by DeadSix27** [comment]
![image](https://user-images.githubusercontent.com/1492505/58198993-d0859280-7ccf-11e9-8ccb-b9001a959794.png)

e.g it looks for `{CUDA_TOOLKIT_ROOT_DIR}/bin/nvcc` for example
where `CUDA_TOOLKIT_ROOT_DIR` is (on windows anyway):
`K:\w2x\NVIDIA GPU Computing Toolkit\CUDA\v10.1\`
So make sure you have `bin/` `include/` etc in `CUDA_TOOLKIT_ROOT_DIR`

**Comment by velara3** [comment]
Great! I found it

    cmake --DCUDA_TOOLKIT_ROOT_DIR=/Developer/NVIDIA/CUDA-10.1/ -DOPENCV_PREFIX=/usr/local/Cellar/opencv/4.1.0_1 .

Now the output is: 

>-- System is: Darwin (Apple)
-- Found CUDA: /usr/local/cuda (found version "10.1") 
-- 
-- Config summary:
-- 	OpenCV: 4.1.0
-- 	OpenCL: 1.2
-- 	CUDA: 10.1
-- 	Unicode: TRUE
-- 	Installing models to: /usr/local/share/waifu2x-converter-cpp
-- 	Not installing docs
-- 	Building for: Unix Makefiles-x86_64
-- 
-- Configuring done
-- Generating done
