### ISSUE TITLE
What are the processor infos mean?

### ISSUE THREAD

**Issue by velara3** [DeadSix27/waifu2x-converter-cpp#165]
When I get the processor it lists (FMA       ) and (OpenCL    ). What does this mean? 

   1: Intel(R) Core(TM)     (FMA       ): num_core=4

**Comment by DeadSix27** [comment]
FMA is using FMA Instruction on the CPU, OpenCL uses.. a (translation layer?) to run OpenCL on the CPU instead of the GPU, kinda like https://aur.archlinux.org/packages/pocl/ does.
