### ISSUE TITLE
Contributing to development how

### ISSUE THREAD

**Issue by velara3** [DeadSix27/waifu2x-converter-cpp#167]
I dont know if it will happen but if I want to help contribute to development what do I need to get setup? I'm on OSX and have experience building apps in other languages (see bio). I don't know what this is C? C++? 

What I would work on is getting some output in JSON formats to start and see how that goes. I have VSC installed (no VS on Mac).

**Comment by DeadSix27** [comment]
We still need a basic Wiki with usage help.. and links to guides and GUI's etc.

And a Issue-template.. that tells the user to provide possible logs.. cmake logs.. build error logs.. system architecture/OS etc etc.

You can submit PRs for that if you want?
