### ISSUE TITLE
Occasionally corrupt output to non-png

### ISSUE THREAD

**Issue by Kattus** [DeadSix27/waifu2x-converter-cpp#169]
I occasionally get corrupted output when the input image is png, and output is webp or jpg, if I output to png it's all good. If I first convert the source image to something like webp (lossless) it will output fine, so I assume there's something wrong with the input file and imagemagick fixes that.

I have a feeling this is related to the newest commits as they do things different with pngs, also this was never an issue before.

![i](https://too.lewd.se/57fe6bb3ea56_2019-05-24_07-28-13.webp)
![m](https://too.lewd.se/d36cee0de1ca_2019-05-24_07-29-22.webp)
![g](https://too.lewd.se/55bb39c1c5b0_2019-05-24_07-31-38.webp)

[source image](https://too.lewd.se/075801cb7ba0_74874826_p0.png)

**Comment by DeadSix27** [comment]
Can you it with this commit: https://github.com/DeadSix27/waifu2x-converter-cpp/commit/f8d5ca0b5ac1e12a0ab863a3379e0bfd4e96b34c

Should occur there too if I'm correct.

**Comment by Kattus** [comment]
Yes, it still happens with that commit, I'll try narrow it down further though.

**Comment by Kattus** [comment]
Things break with 29467b293703e337caf17e402aa36e4f0b08e94a, previous commit is fine.

29467b293703e337caf17e402aa36e4f0b08e94a
![borked](https://too.lewd.se/23ae18787c59_2019-05-24_15-01-45.webp)

9509152bdfcd23e50b9a6c020fa6fba89c749f16
![fine](https://too.lewd.se/08fe4d138174_2019-05-24_15-00-54.webp)
