### ISSUE TITLE
Command arguments for photos and command arguments for illustrations

### ISSUE THREAD

**Issue by velara3** [DeadSix27/waifu2x-converter-cpp#178]
In the references they mention there are settings to use for photos and settings to use for illustrations. I can't seem to find what these settings are in the command arguments. Is it noise_level?

**Comment by YukihoAA** [comment]
This program is not working same as reference. 

Please check readme.md and building.md before you asking question... there is all options that waifu2x-converter-cpp.

actually "issue" is not QnA box, it is more like reporting errors and ask for enhancement... 

i recommend you to connect discord to ask your questions. 

https://discordapp.com/invite/gAvufS2
