### ISSUE TITLE
What's about MIOpen on linux?

### ISSUE THREAD

**Issue by hmsintrepide** [DeadSix27/waifu2x-converter-cpp#18]
Is a MIOpen (with HIP, ROCm, ...) version for AMD GPU on linux is planned ?

https://github.com/ROCmSoftwarePlatform/MIOpen

**Comment by iame6162013** [comment]
This project uses opencl, AMD has 2 opencl drivers for linux: rocm and amdgpu-pro, thus you can use this on linux.
As far as I know the amdgpu-pro driver has no issues with this program.

If you would want this to use HIP (HIP : Convert CUDA to Portable C++ Code), I'd like to know why?

**Comment by DeadSix27** [comment]
@hmsintrepide If you still need help with this say so and I'll reopen this issue.
