### ISSUE TITLE
Faint white border around sprites (alpha images)

### ISSUE THREAD

**Issue by kcghost** [DeadSix27/waifu2x-converter-cpp#183]
I have found that waifu2x-converter-cpp can't really be used on game sprites, because while it produces a *mostly* transparent image, a faint border of white can still be seen around the sprite.
Easily seen here when over a black background:
![headd1](https://user-images.githubusercontent.com/7506642/60511501-2458a380-9ca0-11e9-9769-35f25d75dc6e.png)

I gather some tricky method must be used, because the model itself doesn't handle alpha? Not sure exactly what the best method is, but I know [waifu2x-chainer](https://github.com/tsurumeso/waifu2x-chainer) handles this better and does some logic around splitting the alpha and doing...something with it. The end result from waifu2x-chainer isn't perfect either, it ends up blending with the alpha abit more than it should, but doesn't get a border and is directly usable, especially with some post-processing.

Not sure if it applies to waifu2x, but I have seen [output from Nvidia gameworks](https://drive.google.com/drive/u/0/folders/1BluJVmMmthQWdTY-BUMJ7TJQggP4rzVZ) and other AI scalers that simply don't handle the alpha layer at all and the image bleeds out from the sprite making a blurry mess in the once-transparent areas. Even a mode like that might be useful, cause a mask to cut out the sprite can be generated with xbrz or another scaler that handles transparency well.

**Comment by YukihoAA** [comment]
it maybe caused by border pixel but it is spec of waifu2x-converter-cpp's algorithm.

suggest to use other algorithms for that. sorry.
