### ISSUE TITLE
Noise reduction is not taking effect?

### ISSUE THREAD

**Issue by El-Desconocido** [DeadSix27/waifu2x-converter-cpp#185]
I used the last Windows release, but when I tried to apply noise reduction is not taking effect. The console is normal, as if the file were processed properly (including block processing and elsewhere), but when I open the file there are no changes. It only works when using scaling, but with noise is doing nothing. I tested with GPU and with CPU and there are no changes. The last command that I used looks like the next: "waifu2x-converter-cpp.exe -m noise --noise-level 3 -c 9 --disable-gpu -i C:\Users\user\IMG\source.png -o C:\Users\user\IMG\test.png". I have done something wrong, or there is a bug?

**Comment by YukihoAA** [comment]
This Issue will be fixed by PR #186
