### ISSUE TITLE
Segfault when using cuda, whatever the card

### ISSUE THREAD

**Issue by Duponin** [DeadSix27/waifu2x-converter-cpp#188]
Hi,

I start to use that great software but I encounter that issue: it segfaults when I do a command using cuda core (`--help` is excluded).

When I do without GPU it works.

What information can I provide to help debug?

(I'm using Nvidia's driver up to date with a GTX 1060)

**Comment by Kattus** [comment]
What OS? What is your exact driver version? what version of GCC did you use? anything out of the ordinary while compiling?

**Comment by Duponin** [comment]
Hi,

I use Void Linux. Driver is Nvidia 430.14.
I didn't compile it by myself but used the package.

I tried to compile on my own but it doesn't, it miss CUDA.
Maybe segfault come from there.

**Comment by Kattus** [comment]
The Void Linux version appears to be rather outdated, I'd recommend building it yourself if you can. Or give the package maintainers a poke. This is not a fault or waifu2x-converter-cpp. 

As a temporary workaround, you might have success using `--force-OpenCL`.

**Comment by Duponin** [comment]
Alright. `--force-OpenCL` works well.

Thank you for your time and help.
