### ISSUE TITLE
Add guide on how to train your own models

### ISSUE THREAD

**Issue by DeadSix27** [DeadSix27/waifu2x-converter-cpp#2]
I need help on writing a guide on how to train your own models.

If you know how to do that please reply.

**Comment by max20091** [comment]
1. Put your model folder to waifu2x-converter-cpp location
2. Add "--model_dir <folder>" parameter (for example your folder is "models" then your parameter is "--model_dir models\"

**Comment by max20091** [comment]
parameter list can be found by adding "-h" parameter after waifu2x-converter-cpp.exe

**Comment by DeadSix27** [comment]
I meant training your own models, not using them. I updated the post now, didn't phrase that correctly.

**Comment by max20091** [comment]
You can't training on waifu2x-converter-cpp even you have NVIDIA GPU cuz it doesn't support training models, only convert image.

**Comment by max20091** [comment]
I noticed that there is model training in https://github.com/DeadSix27/waifu2x-converter-cpp/tree/master/appendix/ but I have no idea how to use it :(

**Comment by nagadomi** [comment]
Currently, training is only supported on my implementation. I think it's hard to implement it from scratch.
https://github.com/nagadomi/waifu2x#train-your-own-model
In addition, my implementation has already switched to new architecture called `upconv_7`. waifu2x-converter-cpp supports only old `vgg_7` architecture. If you want to train the model for waifu2x-converter-cpp, you need to specify the `-model vgg_7` option on` train.lua`.
You can export your trained model with:
```
th tools/export_model.lua -i <path to your model> -o my_mode.json
```
This JSON file will work with waifu2x-converter-cpp.

**Comment by DeadSix27** [comment]
@nagadomi on that note, will you keep support/scripts for the old model?

**Comment by FluffyDiscord** [comment]
@DeadSix27 Hey there, I am able to help you with the model training. I have got gtx 1080 ti so it should be fast. If you want me to train new or existing model for this converter, contact me somehow =]

**Comment by YukihoAA** [comment]
Since upconv_7 model uses vgg_7 model too, training vgg_7 is not duplicates to upconv support. (If we supports training vgg_7, it can be use to upconv_7 too)
