### ISSUE TITLE
gcc versions later than 8 are not supported

### ISSUE THREAD

**Issue by Anivice** [DeadSix27/waifu2x-converter-cpp#203]
Currently CUDA doesn't support gcc versions later than 8. I've tried to switch to clang, only to find that nvcc uses gcc by default. Maybe some adjustments can be made or a warning message should be shown here.

**Comment by DeadSix27** [comment]
Pretty sure it works fine with gcc9, just patch the error out somewhere in host_config.h, I forgot where exactly, the error should tell you more.

**Comment by Anivice** [comment]
May I ask a question here. Are you using cuda 10.1? I'm currently dealing with cuda 10.1 and NVIDIA told me that thay do not support gcc9

**Comment by DeadSix27** [comment]
10.1, as i said, patch the error out. Compile and see for yourself.

**Comment by Anivice** [comment]
OK. This works fine now. I wonder what exactly is unsupported in gcc9. This action is not really safe.

**Comment by DeadSix27** [comment]
No clue, maybe nothing and they're just too lazy to update their SDK.
But I have not encountered an issue on my end yet, with anything w2x uses cuda for.
