### ISSUE TITLE
w2xcr linking fails without opencv on windows

### ISSUE THREAD

**Issue by DeadSix27** [DeadSix27/waifu2x-converter-cpp#209]
When setting up CI i noticed that builds without opencv on windows will fail to link against w2cr

```
 w2xcr.obj : error LNK2019: unresolved external symbol __imp_w2xconv_convert_file referenced in function proc_thread [d:\a\waifu2x-converter-cpp\waifu2x-converter-cpp\_build\w2xcr.vcxproj]
         D:\a\waifu2x-converter-cpp\waifu2x-converter-cpp\_build\Release\w2xcr.exe : fatal error LNK1120: 1 unresolved externals [d:\a\waifu2x-converter-cpp\waifu2x-converter-cpp\_build\w2xcr.vcxproj]
```

Also encountering:
```
'__cpuid': identifier not found
```
But only when opencv is missing, so maybe they define it for us or they include `<intrin.h> for us.

Either way, this needs investigation, possibly disable w2xcr without opencv detected during cmake.

**Comment by YukihoAA** [comment]
Actually I found this problem long time ago but i dont remember I fixed on some branch or not. It need to include <intrin.h> on #ifndef HAVE_OPENCV condition and i think it will need some little changes to support it.
