### ISSUE TITLE
Odd issue with other models

### ISSUE THREAD

**Issue by xxprototypexx32** [DeadSix27/waifu2x-converter-cpp#21]
I got v4 working instead of the current build, when I tried using nagadomi's "anime_art_style_rgb" model to upscale an image, mostly the green channel shows up with hints of red and blue. 
Terminal shows no errors though
OSX 10.12.6
http://imgur.com/a/5q6oj

**Comment by nagadomi** [comment]
waifu2x-converter-cpp does not support the latest model of my repo, only supported `models/vgg_7/`.

**Comment by DeadSix27** [comment]
@nagadomi thanks for keeping an eye on this repo too :)

**Comment by DeadSix27** [comment]
Actually @nagadomi, do you have any idea about this issue?: 
https://github.com/DeadSix27/waifu2x-converter-cpp/issues/24

**Comment by ffleader1** [comment]
Thank you for this :D 
Hope to see a solution soon.

**Comment by xxprototypexx32** [comment]
Aww that's a little sad
