### ISSUE TITLE
Other model support?

### ISSUE THREAD

**Issue by rnul** [DeadSix27/waifu2x-converter-cpp#210]
I couldn't find an answer to this in the existing documentation. Is there support for other models outside of the ones supplied by default in this package? I downloaded the models from nagadomi's waifu2x github and while I didn't try every model, from the ones I did try I got completely incoherent output images. Can anyone provide some feedback on this?

**Comment by DeadSix27** [comment]
See: https://github.com/DeadSix27/waifu2x-converter-cpp/issues/200
and https://github.com/nagadomi/waifu2x/tree/master/models/vgg_7

**Comment by rnul** [comment]
> See: #200
> and https://github.com/nagadomi/waifu2x/tree/master/models/vgg_7

can confirm those (photo) work, thanks.
