### ISSUE TITLE
No VS runtime Error

### ISSUE THREAD

**Issue by YukihoAA** [DeadSix27/waifu2x-converter-cpp#218]
![image](https://user-images.githubusercontent.com/20253131/70954566-19a89400-20b1-11ea-9f80-afca89495dff.png)

as waifu2x-converter-cpp is compiled with Release option so need to include VS runtime as static lib. which was available past. need to edit some option to support it again

**Comment by DeadSix27** [comment]
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads ? 
Why static, people install this anyway for games etc. Might as well stay shared and safe some space?

**Comment by YukihoAA** [comment]
actually there is /MT flag so VS runtime should be included which is only includes essential runtime like 1~2KB, while w2xlib is compiled by /MT but waifu2x-converter-cpp exe is compiled by MD not MT so it is weird.

**Comment by DeadSix27** [comment]
kk, I'll look into it

**Comment by DeadSix27** [comment]
So did this actually work then yuki?: https://github.com/DeadSix27/waifu2x-converter-cpp/compare/master...DeadSix27:DeadSix27-mtlib-patch-1

**Comment by YukihoAA** [comment]
@DeadSix27 
![image](https://user-images.githubusercontent.com/20253131/72206498-06cb8880-34d2-11ea-9c66-635552de5ffa.png)


Actually not on w2xcr
