### ISSUE TITLE
Incompatible with vgg_7/art_y model from original waifu2x project

### ISSUE THREAD

**Issue by sternskr** [DeadSix27/waifu2x-converter-cpp#224]
Currently the [art_y model](https://github.com/nagadomi/waifu2x/tree/master/models/vgg_7/art_y) from the original waifu2x project causes the program to throw the following error as it is looking for a noise0_model.json file that is not present. It is compatible with the vgg_7 models from the same page, the lack of noise0 files in the art_y model causes the current release build to throw an exception.

Not sure if this is intentional incompatible or not, so I'm reporting it

![image](https://user-images.githubusercontent.com/14317840/75089667-3353d500-5553-11ea-90ab-05d9d96bac63.png)

**Comment by YukihoAA** [comment]
try #232
