### ISSUE TITLE
[Possible issue] Scaled image are slightly darker

### ISSUE THREAD

**Issue by ffleader1** [DeadSix27/waifu2x-converter-cpp#24]
Apparently, if I upscale and image to x2 it's size, it becomes darker. I don't know why
This album is a good compassion
https://imgur.com/a/WoAAL
The source image and the one used with "lltcggie/waifu2x-caffe" are similar, albeit the size.
The source image and the one used with waifu2x-converter-cpp are slightly different in color, as the later is darker.
All images are in .png, so you can easily download and check it.
Place them side by side, use Windows image viewers and push left-right continuously, you can see the difference.
I don't know why, but apparently the CUDA version gives better results, yet I cannot use it :| Please look into it for AMD GPU users.

**Comment by DeadSix27** [comment]
I see that it makes it a little darker, tested it with a grey-scale test image which seems to shift in color a tiny bit.. strange.. well it was not made for 3D CGI anyway, it was made for 2d no? 

Not sure, either way you better ask that to @nagadomi who has way more knowledge about the models stuff, I basically just made this repo to make sure it still compiles on newer VS and Windows versions (as well as newer OpenCL)

I have barely a clue about how the program actually works (in terms of image manipulation).

But there are many talented people out there that can happily do pull requests on this repo :)
A few already did

**Comment by ffleader1** [comment]
How can I ask him? 
Like should I make a separate issue request on this
https://github.com/nagadomi/waifu2x

**Comment by DeadSix27** [comment]
@ffleader1 Check out https://github.com/DeadSix27/waifu2x-converter-cpp/issues/21

**Comment by nagadomi** [comment]
waifu2x has 2 version of upscaling archtectures, [vgg_7](https://github.com/nagadomi/waifu2x/blob/a1458de3c86de4e6d7860ff8922607b235e3097d/lib/srcnn.lua#L141) and [upconv_7](https://github.com/nagadomi/waifu2x/blob/a1458de3c86de4e6d7860ff8922607b235e3097d/lib/srcnn.lua#L237).
waifu2x-caffe supports both versions(waifu2x-caffe's RGB model=vgg_7, UpRGB model=upconv_7).
waifu2x-converter-cpp supports only vgg_7, it's same as waifu2x-caffe's RGB model I think.

upconv_7 and vgg_7 differ only in the last layer and preprocessing, It is not difficult to implement it, but I do not have AMD GPU and knowlege of OpenCL. If someone is interested in implementing upconv_7, https://rocm.github.io/dl.html might be helpful. waifu2x-caffe uses cuDNN to implement both model, and ROCm seems to be compatible with cuDNN.

**Comment by ffleader1** [comment]
So I guess it means...unfixable in the foreseeable future.
*sighhh*
For those who happen to come across and feel annoying by this problem, here is a way to minimize, not completely solve, the problem.
That is, by using **imagemagick** and add this command:  _-brightness-contrast 0.2_ , you can bring the brightness level close, like very very close to the original one. 
EX: Say your image is: input.png
`input.png -brightness-contrast 0.2 output.png`

**Comment by DeadSix27** [comment]
@ffleader1 With the images you provided, can you test again but with these models?: https://github.com/DeadSix27/waifu2x_test/raw/master/models_photo.7z

**Comment by ffleader1** [comment]
@DeadSix27 oh I just download v5.0. I would love to hel but I got a little #41 :<

**Comment by YukihoAA** [comment]
This is will be continued in: #40
