### ISSUE TITLE
CUDA don't works

### ISSUE THREAD

**Issue by Alex20129** [DeadSix27/waifu2x-converter-cpp#241]
I successfully build the app (OS: Ubuntu 18.04.4 LTS) with CUDA support option, but when i run:
$ ./waifu2x-converter-cpp --list-processor
i see:
 0: AMD Ryzen 7 3700X 8-Core Processor             (FMA    ): num_core=16
im not a specialist, but it looks like the program actually don't try to use exactly CUDA, but uses OpenCL which returns a list of available devices. in my case this list (for some reason) contains just one device - my CPU. how to enforce the program to use CUDA?

**Comment by Kattus** [comment]
Probably has something to do with #233, fixed the opposite problem for me, but I guess CUDA packages work differently on other distros.

**Comment by Alex20129** [comment]
Problem solved after manual re-install older version driver
$ apt install nvidia-opencl-icd-384 nvidia-384 nvidia-cuda-toolkit nvidia-settings
New driver was removed and 384 was installed. After that
$ clinfo -a
Shows "Number of platforms 1" and all works just perfecty.
