### ISSUE TITLE
Problem with custom models (*.caffemodel not supported?)

### ISSUE THREAD

**Issue by Alex20129** [DeadSix27/waifu2x-converter-cpp#242]
i downloaded original models from Nagadomi's repo, but seems like there is no way to use them. when i try to:
**$ ./waifu2x-converter-cpp --model-dir ../models_waifu2x-caffe/photo -i /home/alex/Pictures/1x -o /home/alex/Pictures/2x**
i get an error:
**CUDA: GeForce GTX 1080 Ti
Error : couldn't open ../models_waifu2x-caffe/photo//noise1_model.json
terminate called after throwing an instance of 'std::runtime_error' what():  model load failed: ../models_waifu2x-caffe/photo//noise1_model.json**

**Comment by YukihoAA** [comment]
waifu2x-conveter-cpp is only accepts t7 models. no caffemodel supported.
