### ISSUE TITLE
Not doing much.

### ISSUE THREAD

**Issue by arthurwolf** [DeadSix27/waifu2x-converter-cpp#246]
It's not really changing my picture much. I've seen some very impressive results online upscaling old anime, and here it's like the image is identical. What's wrong?
The command: waifu2x-converter-cpp -m noise-scale -v 4 --noise-level 3 --scale-ratio 1.2 -i frame.png -o test.png

The images:
https://imgur.com/fXmgYzB
https://imgur.com/83zkOeC
They are nearly identical, which wasn't the objective. What am I doing wrong?

**Comment by Wykerd** [comment]
@arthurwolf What was your expected result?

The command did what you told it and removed a lot of noise from you image, see the comparison: 
[https://imgur.com/a/uPzuFjf](https://imgur.com/a/uPzuFjf)

**Comment by arthurwolf** [comment]
I was expecting much better results based on pictures I've seen around. I've since moved on to using Anime4X instead, and I'm getting much better results, so it's all fine, please ignore.

**Comment by nonetrix** [comment]
do you find linking to it I can't find a github for anime4x or etc? also I think it might have been more due to using the wrong algorithm but I could be wrong I don't really know much about this stuff

**Comment by nonetrix** [comment]
most close thing I can find is anime4k and that's a GLSL shader that upscales in real-time

**Comment by nonetrix** [comment]
I'm not having this issue but I still want to try waifu4x out as well
