### ISSUE TITLE
Where can i find models?

### ISSUE THREAD

**Issue by Specy-wot** [DeadSix27/waifu2x-converter-cpp#261]
I'm making a waifu2x GUI using this lib and i was trying to find some other models to use for it, currently i only have RGB and Photo, is there some place where i can find other models?

**Comment by YukihoAA** [comment]
this repo only supports vgg_7 models so its all for now.

**Comment by Specy-wot** [comment]
> this repo only supports vgg_7 models so its all for now.

Ah sad, also just a question, does the upconv models give better results than the vgg_7 ones (I know they aren't compatible) ?

**Comment by YukihoAA** [comment]
These models are works slightly different.

If you want to scale images, upconv_7 would be slightly improved results.

for noise reduction, vgg_7 would be fine.

**Comment by Specy-wot** [comment]
Ok thank you, I was thinking to switch to the caffee one since it has more models and settings but was restrained by its size
