### ISSUE TITLE
Add video support

### ISSUE THREAD

**Issue by iame6162013** [DeadSix27/waifu2x-converter-cpp#27]
Expected behavior: 
Accepts all kinds of image & video formats

Current behavior:
Changed the file extension of all ~inputted~ outputted files to png, we should not to do this.
This prevents all video files to be treated as such.

**Comment by DeadSix27** [comment]
This program should not support video files at all, only images.

**Comment by iame6162013** [comment]
Why shouldn't we add support for video files? They are after all a series of images.
Adding it wouldn't be too much work, you can load video files from opencv.
It would be a good reason to clean up the main file a bit, what do you say?
I'll do the work, because I want it.

**Comment by DeadSix27** [comment]
@iame6162013 Feel free to make it work with images :) If you can do that and have the time, its very appreciated

**Comment by maz-1** [comment]
Why not use vapoursynth?
https://github.com/HomeOfVapourSynthEvolution/VapourSynth-Waifu2x-w2xc

**Comment by maz-1** [comment]
@iame6162013 There is a guide:
http://forum.doom9.org/showthread.php?t=172352

**Comment by DeadSix27** [comment]
@maz-1 I think he wants it built in.

**Comment by laclcia** [comment]
honestly having this algorythm accept video files would be amazing. but i have to say the current version is amazing. having support for openCV/CL for amd card's is making the job's light fast compared to CPU. if there was support for videofiles i would use this even more than i allready do.

**Comment by K4YT3X** [comment]
@nioroso-x3 I've already implemented the automation of that process
https://github.com/K4YT3X/video2x

**Comment by DeadSix27** [comment]
I'll close this for now.. As I have a feeling this will never be added...
also this https://github.com/HomeOfVapourSynthEvolution/VapourSynth-Waifu2x-w2xc/ exists, and is based on this project.
