### ISSUE TITLE
Add image detection without extension?

### ISSUE THREAD

**Issue by DeadSix27** [DeadSix27/waifu2x-converter-cpp#3]
The program crashes when no image extension is given.
Maybe we can add code to auto-detect the image type?
Or error out if that is too much work and or is too unreliable.

Also in todo list: https://github.com/DeadSix27/waifu2x-converter-cpp/issues/1

**Comment by max20091** [comment]
We don't need a auto-detect image, just make a batch file and it will auto convert all images.

`FOR /f "delims=" %%a IN ('dir /b input\*.*') DO call waifu2x-converter-cpp.exe --scale_ratio 2 --model_dir models_rgb\ -m noise_scale --noise_level 3 -i "input\%%a" -o "output\%%~na.png"`

1. Make a input folder and a output folder 
2. Put some images to input folder
3. Run the batch file

**Comment by DeadSix27** [comment]
I mean files without an extension in the input.
It just crashes the program, definitely needs a fix, its not hard to do,ill add that later.

**Comment by YukihoAA** [comment]
@DeadSix27 I created new Pull Request #14  to fix this issue.

**Comment by DeadSix27** [comment]
@YukihoAA merged your change.
