### ISSUE TITLE
 waifu2x-converter-cpp/src/w2xconv.h is in c

### ISSUE THREAD

**Issue by iame6162013** [DeadSix27/waifu2x-converter-cpp#30]
Nothing against c, it's just an oxymoron to call your project to be in cpp when using c.

**Comment by DeadSix27** [comment]
@iame6162013 heh, I kept as much of the fork as possible, the name was like that when I forked it. I do not intend to change it.. it's just the name. (nor was it ever my choice)

**Comment by maciozo** [comment]
I think that @iame6162013 just means that you could remove the `#ifdef __cplusplus` blocks by renaming the file to .hpp.

**Comment by iame6162013** [comment]
@maciozo nah, we don't need to rename it, you can use .h in c++ projects, but updating it from c to c++ is handy. Working in w2xconv.cpp atm and c can be a little unhandy.

**Comment by iame6162013** [comment]
I was just wondering if updating it to c++ would have any repercussions.

**Comment by maciozo** [comment]
It could be done, but I don't see much point other than for cosmetic purposes. Would it be to make the pointers a bit nicer? Or to convert structures to classes?

**Comment by iame6162013** [comment]
Having structs which have an constructor for example is handy, not required. 
Being required to say struct prior to using a struct in a function argument feels fairly superfluous to me.
And seeing how this program is written, being more concise is important. 

An example of why I think this program is written oddly: w2xconv_convert_file has a built in png decoder to see what the background color of an image is, I'd have expected a bit more abstraction.

**Comment by DeadSix27** [comment]
Any idea about the deprecation of '_ReadBarrier' and '_WriteBarrier' in threadPool.cpp ?
That's what makes it fail to compile, reason: https://msdn.microsoft.com/en-us/library/65tt87y8.aspx

It's beyond my knowledge in c++ and I couldn't find a easy replacement for those 2 functions guess it needs a rewrite, but i don't know how.

**Comment by iame6162013** [comment]
I'm not too accustomed to waifu2x yet, may I ask what is threadPool.cpp used for?

> The _ReadBarrier, _WriteBarrier, and _ReadWriteBarrier compiler intrinsics and the MemoryBarrier macro are all deprecated and should not be used. For inter-thread communication, use mechanisms such as atomic_thread_fence and std::atomic<T>, which are defined in the C++ Standard Library. For hardware access, use the /volatile:iso compiler option together with the volatile keyword.

I'm not too familiar with multithreading, so it'd take some time to re-implement it.

**Comment by DeadSix27** [comment]
@iame6162013 I went through it, i use _mm_mfence on VS2017 now, which seems to work and compile fine ?

But I ran into other isssues with older PR's of you, ill compile each PR up to the point it fails and report back.

**Comment by DeadSix27** [comment]
@iame6162013 This causes compile issues:
https://github.com/DeadSix27/waifu2x-converter-cpp/commit/613761aaefa7ebd2bfc88d11accb4bd5ef6c8c53

**Comment by DeadSix27** [comment]
We should probably fix the above issues or revert to before this got added

**Comment by iame6162013** [comment]
> LINK : fatal error LNK1181: cannot open input file 'stdc++fs.lib' [G:\w2x\waifu2x-converter-cpp\output\waifu2x-converter-cpp.vcxproj]

That's odd, I'm not too familiar with visual studio sadly.

> cannot convert argument 1 from 'std::experimental::filesystem::v1::path' to 'std::string'
That should be an easy fix. We need to use ".string()" on the path. 

http://en.cppreference.com/w/cpp/experimental/fs/path/native

But would you please review / merge my pr this way I won't have to do double work. I moved some stuff around in main.

**Comment by iame6162013** [comment]
One sec, I'll add it to the PR.

**Comment by iame6162013** [comment]
Added it to the pr, would you please check if it will compile if you remove "stdc++fs" in target_link_libraries in CMakeLists.txt

Sadly I need to go now, maybe I'll have time to look into the issue tomorrow.

**Comment by DeadSix27** [comment]
Sadly the `_wfopen` causes more issues with types not being correct, would require further rewriting, so you should change that back to fopen for windows too, see https://github.com/DeadSix27/waifu2x-converter-cpp/pull/29/files#diff-2a8f5272be33517914ad6fd8a68c7752R1279

**Comment by DeadSix27** [comment]
I tested removing stdc++fs before and yes it does work, however i still run into these issues:

```
"G:\w2x\waifu2x-converter-cpp\output\Project.sln" (default target) (1) ->
"G:\w2x\waifu2x-converter-cpp\output\ALL_BUILD.vcxproj.metaproj" (default target) (2) ->
"G:\w2x\waifu2x-converter-cpp\output\waifu2x-converter-cpp.vcxproj.metaproj" (default target) (16) ->
"G:\w2x\waifu2x-converter-cpp\output\waifu2x-converter-cpp.vcxproj" (default target) (17) ->
(ClCompile target) ->
  G:\w2x\waifu2x-converter-cpp\src\main.cpp(96): error C2131: expression did not evaluate to a constant [G:\w2x\waifu2x-converter-cpp\output\waifu2x-converter-cpp.vcxproj]
  G:\w2x\waifu2x-converter-cpp\src\main.cpp(168): error C2664: 'int w2xconv_convert_file(W2XConv *,const char *,const char *,int,double,int)': cannot convert argument 3 from 'const std::experimental::filesystem::v1::path::value_type *'
to 'const char *' [G:\w2x\waifu2x-converter-cpp\output\waifu2x-converter-cpp.vcxproj]
  G:\w2x\waifu2x-converter-cpp\src\main.cpp(320): error C2664: 'void convert_file(convInfo,std::experimental::filesystem::v1::path,std::string)': cannot convert argument 3 from 'std::experimental::filesystem::v1::path' to 'std::string'
[G:\w2x\waifu2x-converter-cpp\output\waifu2x-converter-cpp.vcxproj]
  G:\w2x\waifu2x-converter-cpp\src\main.cpp(332): error C2664: 'void convert_file(convInfo,std::experimental::filesystem::v1::path,std::string)': cannot convert argument 3 from 'std::experimental::filesystem::v1::path' to 'std::string'
[G:\w2x\waifu2x-converter-cpp\output\waifu2x-converter-cpp.vcxproj]
  G:\w2x\waifu2x-converter-cpp\src\main.cpp(347): error C2664: 'void convert_file(convInfo,std::experimental::filesystem::v1::path,std::string)': cannot convert argument 3 from 'std::experimental::filesystem::v1::path' to 'std::string'
[G:\w2x\waifu2x-converter-cpp\output\waifu2x-converter-cpp.vcxproj]
```

**Comment by iame6162013** [comment]
Oh, found the issue why those crashes happen, give me a min.

**Comment by DeadSix27** [comment]
I do not intend to give up Windows support.
Nor do Intend to cross compile this in the future, that's too messy.. look at all the other effort that goes into that by looking at my other main repo..

And about the stdc++fs, if there is no alternative to windows, either double-code it, e.g make code for windows and for linux and separate by ifdefs or completely rewrite it to not use that library.

Anyway:
Remaining issues:
```
G:\w2x\waifu2x-converter-cpp\src\main.cpp(96): error C2131: expression did not evaluate to a constant [G:\w2x\waifu2x-converter-cpp\output\waifu2x-
converter-cpp.vcxproj]
  G:\w2x\waifu2x-converter-cpp\src\main.cpp(168): error C2664: 'int w2xconv_convert_file(W2XConv *,const char *,const char *,int,double,int)': cannot
 convert argument 2 from 'const std::experimental::filesystem::v1::path::value_type *' to 'const char *' [G:\w2x\waifu2x-converter-cpp\output\waifu2x
-converter-cpp.vcxproj]
```

**Comment by iame6162013** [comment]
> I do not intend to give up Windows support.

That's good, I intend to make any change required on my end to help.

>And about the stdc++fs, if there is no alternative to windows, either double-code it, e.g make code for windows and for linux and separate by ifdefs or completely rewrite it to not use that library.

It's part of the c++ spec http://en.cppreference.com/w/cpp/filesystem
The vs team also supported the TR2 filesystem library in Visual Studio 2012, so it must be able to work somehow. Source: http://cpprocks.com/introduction-to-tr2-filesystem-library-in-vs2012/

I do thank you for checking if my code compiles on windows, I've had numerous issues with visual studio in the past, when trying to get the project to compile. :)

Are you using vs 2017 community now because if so, I may need to look into my issues and if I can reproduce them report them.

I'll post another 'blind' (see above as to why it's blind) patch to try and resolve the issue.

**Comment by DeadSix27** [comment]
@iame6162013 Ye I updated to OpenCV 3.3 and VS2017, the code compiles fine without including any stdc++fs equivalent right now, maybe its auto included in vs? idk

**Comment by iame6162013** [comment]
>  the code compiles fine without including any stdc++fs equivalent right now, maybe its auto included in vs? idk

Do you mean that the current master brach compiles or also my pr?

**Comment by iame6162013** [comment]
> Needs a change to use _mm_mfence() tho, I am not sure how good that change is but it works.

Add a pr, people will review it.

**Comment by DeadSix27** [comment]
@iame6162013 Waiting for you to fix the remaining issues: https://github.com/DeadSix27/waifu2x-converter-cpp/issues/30#issuecomment-328608960

And then ill pr it

**Comment by iame6162013** [comment]
The issues described above should be fixed.

**Comment by DeadSix27** [comment]
@iame6162013 Now the only ones left are:

> "G:\w2x\waifu2x-converter-cpp\output\Project.sln" (default target) (1) ->
> "G:\w2x\waifu2x-converter-cpp\output\ALL_BUILD.vcxproj.metaproj" (default target) (2) ->
> "G:\w2x\waifu2x-converter-cpp\output\waifu2x-converter-cpp.vcxproj.metaproj" (default target) (16) ->
> "G:\w2x\waifu2x-converter-cpp\output\waifu2x-converter-cpp.vcxproj" (default target) (17) ->
> (ClCompile target) ->
>   G:\w2x\waifu2x-converter-cpp\src\main.cpp(96): error C2131: expression did not evaluate to a constant [G:\w2x\waifu2x-converter-cpp\output\waifu2x-converter-cpp.vcxproj]
>   G:\w2x\waifu2x-converter-cpp\src\main.cpp(168): error C2664: 'int w2xconv_convert_file(W2XConv *,const char *,const char *,int,double,int)': cannot convert argument 2 from 'const std::experimental::f
> ilesystem::v1::path::value_type *' to 'const char *' [G:\w2x\waifu2x-converter-cpp\output\waifu2x-converter-cpp.vcxproj]

**Comment by iame6162013** [comment]
I don't think you pulled my changes prior to trying to build w2x :)

**Comment by DeadSix27** [comment]
@iame6162013 you are right, was a caching issue.. anyway this is the actual remaining issue:

```
(ClCompile target) ->
  G:\w2x\waifu2x-converter-cpp\src\main.cpp(165): error C2664: 'int w2xconv_convert_file(W2XConv *,const char *,const c
har *,int,double,int)': cannot convert argument 3 from 'const std::experimental::filesystem::v1::path::value_type *' to
 'const char *' [G:\w2x\waifu2x-converter-cpp\output\waifu2x-converter-cpp.vcxproj]
```

**Comment by iame6162013** [comment]
Could you check the above commit if it currently works on windows?

**Comment by DeadSix27** [comment]
add to work arround the stdc++fs VS issue for now:
```
if(MSVC)
	target_link_libraries(waifu2x-converter-cpp LINK_PUBLIC w2xc)
  else()
	target_link_libraries(waifu2x-converter-cpp LINK_PUBLIC w2xc stdc++fs)
  endif()
```
Beside that the other issues are fixed

**Comment by iame6162013** [comment]
Commit the above, I think it's ready to merge.

**Comment by DeadSix27** [comment]
@iame6162013 You compile on linux right?
How do you do it?
```
$ ./waifu2x-converter-cpp  --list-processor
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```
gdb bt full: https://gist.github.com/DeadSix27/1d01d50467f60cc4f00b3389a2eafdc6

**Comment by iame6162013** [comment]
> ./waifu2x-converter-cpp  --list-processor

Runs perfectly fine on my hardware, could you post the result of clinfo (you may need to install it)
And your system specs, gpu/cpu etc?

**Comment by DeadSix27** [comment]
@iame6162013 
clinfo: https://gist.github.com/DeadSix27/74d5333e7129f15625530048589b738a
the gpu is the iGPU of the Intel(R) Pentium(R) CPU G4620 @ 3.70GHz
which is a HD 630.

**Comment by iame6162013** [comment]
It may be that clover has issues, try beignet.

**Comment by iame6162013** [comment]
And please open a new issue when it's completely off topic, just so I can find where you posted what.

**Comment by DeadSix27** [comment]
@iame6162013 Can you join the discord?

**Comment by iame6162013** [comment]
I don't have discord sadly, I'll see if I can make one, if I do, it will be under the same name.
