### ISSUE TITLE
Success in scale size 2 but crash when scale size 5 or 10

### ISSUE THREAD

**Issue by darklx** [DeadSix27/waifu2x-converter-cpp#32]
Hello,

I have tried two different image file, both have this issue.

Version:v4.0 release of waifu2x-converter-cpp compiled with OpenCV (Windows 64 AMD) 

Argument:
`waifu2x-converter-cpp -i "..\1.jpg" -m noise_scale -j 8 --scale_ratio 5 --noise_level 2`

File Info:
3200x2000 pixel

**Comment by kah0922** [comment]
The only resize model included with waifu2x-converter-cpp is 2x.

**Comment by darklx** [comment]
OK，Thank you！
