### ISSUE TITLE
Move The LLVM Bin To Another Location

### ISSUE THREAD

**Issue by kah0922** [DeadSix27/waifu2x-converter-cpp#33]
If one creates a package of waifu2x-converter-cpp, which installs the executable into /usr/bin and forces OpenCL, the program will SEGFAULT as it can't create the LLVM bin file, unless you run it as root. All subsequent runs will work.

A better location for the binary that won't cause SEGFAULTS is /home/(user)/,local/share .

**Comment by DeadSix27** [comment]
@kah0922  I think i have a working fix for that, but you'd have to test it, would you?

**Comment by kah0922** [comment]
As long as I can test it with the package I maintain [here](https://build.opensuse.org/package/show/home:kah0922/waifu2x-converter-cpp), then sure.

**Comment by DeadSix27** [comment]
Define "testing with the package you maintain"
I can offer you fixed source code in a fixed branch and you can compile it however you want, is that sufficient?

**Comment by kah0922** [comment]
That should work. I won't get a chance to test until much later today though.

**Comment by DeadSix27** [comment]
@kah0922 https://github.com/DeadSix27/waifu2x-converter-cpp/tree/cl_binary_test

Check out this branch and report if this works

**Comment by kah0922** [comment]
It's not compiling. I've tried clang and gcc.
https://build.opensuse.org/package/live_build_log/home:kah0922:branches:home:kah0922/waifu2x-converter-cpp/openSUSE_Tumbleweed/x86_64

**Comment by DeadSix27** [comment]
@kah0922 compiles fine on ubuntu 17

What is your OS? Cmake command line, cmake output and you are running 64 bit right?

**Comment by kah0922** [comment]
That seemed to work.
For the record, I'm using the OpenBuildService (OBS) to create a package. What I linked to earlier was the build log, and everything starts from scratch on every rebuild.

**Comment by DeadSix27** [comment]
@kah0922 can you you the full cmake output with the newest push and tell me if you saw `if this line shows up, report it to DeadSix`

**Comment by kah0922** [comment]
I did. The full log is [here](https://build.opensuse.org/build/home:kah0922:branches:home:kah0922/openSUSE_Tumbleweed/x86_64/waifu2x-converter-cpp/_log).

**Comment by DeadSix27** [comment]
@kah0922 You "did"? I see no link past the post of me saying I added a new fix..

And the original post of your log file has not been edited, so I assumed you have not yet posted a log.

And the new link does not work.

**Comment by kah0922** [comment]
Strange, I can view the build log from here. Here's a gist of the log then.
https://gist.github.com/kah0922/6518498483f4b702d1653c8a9e959912
And here's the link to the package.
https://build.opensuse.org/package/show/home:kah0922:branches:home:kah0922/waifu2x-converter-cpp

**Comment by DeadSix27** [comment]
Okay, run once more with the newest change I pushed to:
https://github.com/DeadSix27/waifu2x-converter-cpp/tree/cl_binary_test

Then post the output again, I am only interested in the cmake output if the build succeeds, if it does not compile.. THEN i need the compile output

**Comment by kah0922** [comment]
[Here's the CMake part of the build log.](https://gist.github.com/kah0922/009555a5c21c8932ac3142f8b49fbe9f)

`[ 94s] -- We are on: Linux -> UNKNOWN`
I assume that's the line you're looking for.

**Comment by DeadSix27** [comment]
@kah0922 Ye that's correct.

Anyway there's nothing left on my end, if it compiles fine, go ahead and test the binary file handling, should be in ~/.waifu2x/*.bin 
Not you'll still need to define the model location by --model_dir or w/e the argument was

**Comment by kah0922** [comment]
Finally was able to test it and yes, it works.

**Comment by DeadSix27** [comment]
@kah0922 No issues so far? Anything you don't like? Any problem with it ? 

That while loop I use in the file checking.. not sure If that is a good idea, but it's the best i came up with.. 

Also, would it be a good idea to make the program check the above home dir as well for models?

Or do you prefer the old method, where you HAVE TO define the model folder unless its in the same folder as the binary.

I was going to try to make it search in HOME too but if people don't want that.

**Comment by kah0922** [comment]
I didn't even tell it where the model folder was, it automatically knew it was in /usr/share/waifu2x-converter-cpp (the default location when installed via the CMake option).

No real issues. Mesa's OpenCL for AMD worked fine, pocl failed, but that might have something to do with openSUSE recently fixing their LLVM implementation, so I wouldn't worry about that. I can't test Beignet for Intel as that's also currently broken for openSUSE.

**Comment by DeadSix27** [comment]
@kah0922 I tested beignet on Ubuntu 17.04, works fine there and I did test Mesa AMD on Ubuntu 17.04 too, when i still had the old AMD APU, but I upgraded my home server to a skylake cpu (thus beignet)


About the /usr/share/ model folder.. I didn't even know it searches there 🙃 .. I did not yet inspect that code (which I would have done (or will do) if I look into adding more search paths for the mode folder)

But ye happy to see it works now.. I will clean up the code later (1 week tops) and push it to master.

If it's a problem to keep the opensuse package on a test-branch I can generate temporary patch if you want.. ah wait github's lovely for that:

https://github.com/DeadSix27/waifu2x-converter-cpp/compare/master...DeadSix27:cl_binary_test.patch

:) There's a patch if that's better

**Comment by DeadSix27** [comment]
@kah0922 I merged the changes into master now.
