### ISSUE TITLE
Tried to build with an NVIDIA GPU but it crashes when trying to use the CUDA processor

### ISSUE THREAD

**Issue by LuminescentMoon** [DeadSix27/waifu2x-converter-cpp#35]
Using cuda_9.0.176_win10
Using cmake-3.10.0-rc1-win64-x64
Using OpenCV 3.3.0

Didn't install the AMD APP SDK.

Trying to build it originally fails because CUDA 9 does not support `sm_20` architecture so I've commented out [L226-L230](https://github.com/DeadSix27/waifu2x-converter-cpp/blob/0fa57238c38997410737a04acdc3abef8911615d/CMakeLists.txt#L226-L230), [L238-L242](https://github.com/DeadSix27/waifu2x-converter-cpp/blob/0fa57238c38997410737a04acdc3abef8911615d/CMakeLists.txt#L238-L242), and removed `modelHandler_CUDA.ptx20.h` at [L249](https://github.com/DeadSix27/waifu2x-converter-cpp/blob/0fa57238c38997410737a04acdc3abef8911615d/CMakeLists.txt#L249) in [CMakeLists.txt](https://github.com/DeadSix27/waifu2x-converter-cpp/blob/0fa57238c38997410737a04acdc3abef8911615d/CMakeLists.txt).

I also had to comment out [L18-L20](https://github.com/DeadSix27/waifu2x-converter-cpp/blob/0fa57238c38997410737a04acdc3abef8911615d/src/modelHandler_CUDA.cpp#L18-L20) and replace [L139-L142](https://github.com/DeadSix27/waifu2x-converter-cpp/blob/0fa57238c38997410737a04acdc3abef8911615d/src/modelHandler_CUDA.cpp#L139-L142) with `const char *prog = prog30;` in [modelHandler_CUDA.cpp](https://github.com/DeadSix27/waifu2x-converter-cpp/blob/0fa57238c38997410737a04acdc3abef8911615d/src/modelHandler_CUDA.cpp).

Now when I try to run it using CUDA, this happens:

```
PS C:\Users\Christianity\Pictures> 2x --list-processor
   0: GeForce GTX 1080 Ti                          (CUDA      ): num_core=28
   1: GeForce GTX 1080 Ti                          (OpenCL    ): num_core=28
   2: AMD Ryzen 7 1700 Eight-Core Processor          (FMA       ): num_core=16
PS C:\Users\Christianity\Pictures> 2x .\Thanks.png -m scale --processor 0
CUDA: GeForce GTX 1080 Ti
start scaling
#1 2x scaling...
```

and then the windows error reporting dialog appears.

OpenCL works fine though.

**Comment by LuminescentMoon** [comment]
Never mind. My PATH was pointing to an older version. With the above changes, CUDA works perfectly.

**Comment by DeadSix27** [comment]
@LuminescentMoon Trying to get cuda to work, how did you avoid: modelHandler_CUDA.cpp(22): fatal error C1083: Cannot open include file: 'modelHandler_CUDA.ptx30.h': No such file or directory
