### ISSUE TITLE
Compilation fails with CUDA enabled

### ISSUE THREAD

**Issue by ignaciobfp** [DeadSix27/waifu2x-converter-cpp#37]
Hello,

I have an nVidia GPU, and I wanted to test CUDA. I had to make the changes described in #35 (every one of them) to make it work. My situation was the same, I followed the BUILD.md guide but installing CUDA instead of AMD SDK.

After that It seems to work with no issues. Performance seems good, but as my understanding of CUDA specifics is very limited, I am not sure what are the effects of this workarround. I would like to help with testing if needed.

**Comment by DeadSix27** [comment]
> After that It seems to work with no issues. Performance seems good,
But compilation fails?
So what does work with no issues?

**Comment by ignaciobfp** [comment]
I apologize since my explanation was not clear enough.

Compilation fails with the code "as is" on master. With the changes suggested in #35 it compiles and works, but my knowledge of what is happening behind the scenes is not enough to make a PR with a proper fix (not just a workaround commenting the offending lines).

**Comment by DeadSix27** [comment]
@ignaciobfp Ah, ye now I understand, I will look into PR'ing it

**Comment by ignaciobfp** [comment]
Nice, thanks

**Comment by DeadSix27** [comment]
@ignaciobfp Don't expect it too soon though, ill leave this issue open until I PR it tho

**Comment by LuminescentMoon** [comment]
Removing sm_20 support (what I've show in my issue) just means that this program would no longer support older GPUs.

**Comment by YukihoAA** [comment]
If your error message is "Unsupported Visual Studio Version Error"
Maybe reason is your VS version.

reference: "https://devtalk.nvidia.com/default/topic/1022648/cuda-setup-and-installation/cuda-9-unsupported-visual-studio-version-error/post/5208390/#5208390"

**Comment by thebombzen** [comment]
Is this still a problem in git master? See #54.

**Comment by YukihoAA** [comment]
@DeadSix27 @ignaciobfp 
This issue has been solved in #54, It should be closed.

**Comment by DeadSix27** [comment]
@YukihoAA I added you as contributor you have push rights and can close issues now.
see: https://github.com/DeadSix27/waifu2x-converter-cpp/invitations

**Comment by YukihoAA** [comment]
@DeadSix27 Thank you for your invitation!

OK, I'll keep check on new PR and issues
