### ISSUE TITLE
[Question] Using waifu2x_win_koroshell with the latest version of waifu2x-converter-cpp

### ISSUE THREAD

**Issue by ffleader1** [DeadSix27/waifu2x-converter-cpp#38]
So this maybe a dump question.
1) So I was using waifu2x_win_koroshell download fron [here](http://inatsuka.com/extra/koroshell/) like the instruction. That version is supposed to be very old if I am not mistaken? So I downloaded the latest release of you, and overwrite every files. Is it suppose to be the correct way to no this? I hope not.
I don't know how to implement the latest release to that waifu2x_win_koroshell. 
2) Also, I am fine with using command line, but I don't know how to convert multiple images, maybe a folder of images with the command. Like what is the syntax for converting an entire folder?
3) Finally, the last release was from Dec last year. Any release coming soon with OpenCV 3.3 (not sure if it's important anyway)?

**Comment by DeadSix27** [comment]
@ffleader1 
1) Nothing to be overwritten, download the release of my fork and use no other binary, my fork only has command line, there is a GUI inside but I never touched it, not sure if it works, I wouldn't count on it.

2) Scaling multiple images would work like `waifu2x-converter-cpp.exe -i test_folder_of_images --scale_ratio 4 -o test_folder_scaled` but that does not yet work, I will compile once @iame6162013 checks 1 more thing

3) see above

**Comment by DeadSix27** [comment]
@ffleader1 try: https://github.com/DeadSix27/waifu2x-converter-cpp/releases/tag/5.0
