### ISSUE TITLE
Unicode support on windows

### ISSUE THREAD

**Issue by DeadSix27** [DeadSix27/waifu2x-converter-cpp#4]
imread() in OpenCV has no support for unicode as it seems.

Needs a work-around as suggested in:
http://stackoverflow.com/questions/24769623/opencv-imread-on-windows-for-non-ascii-file-names
http://answers.opencv.org/question/103013/imwrite-with-unicode-path-windows/

Maybe: https://msdn.microsoft.com/en-us/library/windows/desktop/dd374130%28v=vs.85%29.aspx

**Comment by YukihoAA** [comment]
https://stackoverflow.com/questions/43360543/open-image-files-with-unicode-names-using-imread?rq=1

This solution will give you proper way of using unicode in OpenCV

**Comment by DeadSix27** [comment]
@YukihoAA I'll look into it later, but I'm very busy usually. So maybe won't try to implement that right away, but seems easy enough.

**Comment by DeadSix27** [comment]
@YukihoAA Feel free to join my discord: https://discord.gg/k7eH2V too
