### ISSUE TITLE
Add upconv_7 model support

### ISSUE THREAD

**Issue by DeadSix27** [DeadSix27/waifu2x-converter-cpp#40]
See: https://github.com/DeadSix27/waifu2x-converter-cpp/issues/24#issuecomment-327324009
For more information

**Comment by kah0922** [comment]
Any progress on this? Like, for example, using [HIP ](https://github.com/ROCm-Developer-Tools/HIP)to convert compile CUDA of OpenCL?

**Comment by DeadSix27** [comment]
Sadly no, not my expertise and so far no one contacted me on this, but I will update it once someone does show interest in adding support.

**Comment by YukihoAA** [comment]
See: https://github.com/DeadSix27/waifu2x-converter-cpp/blob/upconv_7/models_upconv/model%20analysis.txt

Ok I analyzed model files and I found some problems we have.

1. vgg_7 only uses nn.SpatialConvolutionMM class but upconv_7 and other architecture use nn.SpatialFullConvolution either.
2. vgg_7 only has 7 phases but cunet & upcunet has 30 phases
3. vgg_7 only uses dH:1, dW:1, kW:3, kH:3, padW:0, padH:0 but other architecture have many variations
4. actually, vgg_7 is not for resize so someone added some algorithm to force conversion we have to get rid of that code. (vgg_7 convert: no more than scale 2.0...)
5. scale_factor and offset has many variation yeeeeee
6. waifu2x-converter-cpp does not support nInputplane 256 in code. we only have 128 and we have to implement filter functions for each converting type (128->256, 256->128, etc.)

**Comment by nagadomi** [comment]
I think that implementing cunet/upcunet without using neural network frameworks is difficult because it is a very complicated architecture. https://github.com/nagadomi/waifu2x/blob/dev/appendix/arch/upcunet.txt
Implementing upconv_7 is not so difficult. It only needs to implement deconvolution layer(SpatialFullConvolution, it is backward pass of convolution).

**Comment by YukihoAA** [comment]
@nagadomi Thank you for your advise!

then, If we implement upconv_7 only, milestone would be set:

- [ ] implement SpatialFullConvolution

- [ ] support various scale_factor, offset, dH, dW, kW, kH, padW, padH in convert function parameter.

- [ ] we need to add/remove code to use upconv_7 for scale convertion.

- [ ] add filter functions for each converting type (128->256, 256->128, 256->3, etc.)

**Comment by YukihoAA** [comment]
I have no idea what is the Spatial Full Convolution do .... I have no experience with CNN, so.. if someone give me hints, it will be help. (I try to learning CNN now, but it will take long time maybe)

**Comment by YukihoAA** [comment]
I read many documents and i tried to implement deconvolution (transposed convolution) but it is too hard and I have no idea why it does not work.... someone may continue work with upconv branch...

**Comment by YukihoAA** [comment]
I will implement upconv_7 using cv::dnn with caffemodel,

torch7 model is not working on cv::dnn

**Comment by YukihoAA** [comment]
my upconv_7 implementation with caffemodel is no available on ```upconv_caffe``` branch.

**Comment by YukihoAA** [comment]
replaced by #235
