### ISSUE TITLE
v5.0 crashing

### ISSUE THREAD

**Issue by ffleader1** [DeadSix27/waifu2x-converter-cpp#41]
I just download v5.0 and, while v4.0 works fine for me:
![image](https://user-images.githubusercontent.com/15016720/31850650-20eac456-b680-11e7-8ed7-503bfd7db030.png)
v5.0:
![image](https://user-images.githubusercontent.com/15016720/31850686-bcbb5a9e-b680-11e7-8e1d-11cfda9d5818.png)
As you can see, there is a bit of diversity.
PC:
- Windows 10 64 bit
- Ryzen R7 1700
- 16GB RAM
- HD 7770 (I know, it suck)

**Comment by DeadSix27** [comment]
Can you send me the image file, do not use imgur, attach it in this issue post?

**Comment by DeadSix27** [comment]
@ffleader1 And also post the full input command line and the output (use https://gist.github.com for the output)

**Comment by ffleader1** [comment]
The file is here, but even .png file crashes too. I think everything.
https://drive.google.com/file/d/0B9qXA8yclPg6OE90MUdYVllkU2c/view?usp=sharing
the command is just normal
The input command is quite standard I think:
`waifu2x-converter-cpp -i bg012.bmp --scale_ratio 2 -o bg012.png`
I am not sure how to use gist to produce the output.

**Comment by DeadSix27** [comment]
@ffleader1 Can you give me a stacktrace via GDB? 
If you don't know how to use it, either find and download a windows build yourself, or download it of me here: https://files.dsix.site/binaries/amd64/gdb/

You then put the gdb.exe in the same folder as waifu2x, run "gdb waifu...exe" in a console, then it will show "(gdb)", type "r <your arguments>", like "r -i image.png -o outimg.png"

**Comment by ffleader1** [comment]
`E:\Game Engine\Crass-0.4.14.0.bin\testwf2x>gdb waifu2x-converter-cpp.exe
GNU gdb (GDB) 8.0.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from waifu2x-converter-cpp.exe...(no debugging symbols found)...done.
(gdb) r -i bg012.bmp --scale_ratio 2 -o bg012.png
Starting program: C:\Program Files\waifu2x-converter-cpp-win64_DeadSix27_v5\waifu2x-converter-cpp.exe -i bg012.bmp --scale_ratio 2 -o bg012.png
[New Thread 1332.0xd60]
[New Thread 1332.0x22d4]
[New Thread 1332.0x1110]
[New Thread 1332.0xfdc]
gdb: unknown target exception 0xc0000409 at 0x7ffbd422505c

Thread 1 received signal ?, Unknown signal.
0x00007ffbd422505c in w2xconv_test () from C:\Program Files\waifu2x-converter-cpp-win64_DeadSix27_v5\w2xc.dll`
![image](https://user-images.githubusercontent.com/15016720/31852361-b2ded7ba-b6a0-11e7-8fec-cd78b0a4f0a2.png)

**Comment by DeadSix27** [comment]
@ffleader1 I forgot to say type "bt" after, sorry

**Comment by ffleader1** [comment]
sorry, type "bt" after what?
after output file name?
I got the PARSE ERROR: Argument: bt
        Couldn't find match for argument

**Comment by DeadSix27** [comment]
@ffleader1 
As described here:
> you then put the gdb.exe in the same folder as waifu2x, run "gdb waifu...exe" in a console, then it will show "(gdb)", type "r ", like "r -i image.png -o outimg.png" then it should crash
Do that, then: when still in (gdb) you type bt like: "(gdb) bt" then upload to pastebin, then "(gdb) bt full" then upload to pastebin

**Comment by ffleader1** [comment]
like this? https://pastebin.com/bad1Hd4p

**Comment by DeadSix27** [comment]
@ffleader1 correct, but I forgot windows build isnt debug ofc, try this version of w2x and do the same gdb stuff I said before: https://files.dsix.site/binaries/amd64/waifu2x/waifu2x-converter-cpp_51_debug.7z

**Comment by DeadSix27** [comment]
@ffleader1 I just realised that the windows builds are Visual studio ofc.. and I usually compile with gcc/g++... so the gdb wont be able to help us.. you do not happen to have Visual studio installed? if not.. then this might take longer as ill have to look into cross compiling w2x.. :|

**Comment by ffleader1** [comment]
Hmmm, is Visual studio free?

**Comment by DeadSix27** [comment]
@ffleader1 community edition is, ye but its a little big (5ish gb) and i feel like too complicated...

But if you can't wait then ye it would speed things up if you can install it and run debug with it

**Comment by DeadSix27** [comment]
@iame6162013 You have any better idea? I never really thought about debugging crashes of VS compiled binaries on other peoples system.. remote debugging is a thing but idk how that works..

I usually just told people to quickly get gdb and run a few commands.. but ye I forgot i'm not cross compiling this.

**Comment by ffleader1** [comment]
Hmmm, so I can download it from here right?
https://www.visualstudio.com/downloads/
I have the Enterprise Edition but I have never used it.
But if you want gcc/g++ compiler, I have Cygwin installed already...

**Comment by DeadSix27** [comment]
@ffleader1 I never tested cygwin. Theres already a lot of  work to be done to cross compile it, doubt cygwin would work right now.

And ye that is the download link, direct one: https://www.visualstudio.com/thank-you-downloading-visual-studio/?sku=Community&rel=15

**Comment by ffleader1** [comment]
I am stuck at this step though, what to tick?
![image](https://user-images.githubusercontent.com/15016720/31853593-44fb4200-b6b5-11e7-8893-933450e2a402.png)

**Comment by DeadSix27** [comment]
@ffleader1 Desktop Dev C++, rest unticked

**Comment by ffleader1** [comment]
yeah 5.57GB
see you tomorrow then.

**Comment by DeadSix27** [comment]
@ffleader1 Do you have traffic limits or just slow net? If limits don't worry, I'll eventually figure out how to cross compile it and then we can use gdb.. otherwise see you tomorrow i guess

**Comment by ffleader1** [comment]
Oh I don't actually. It's done.

**Comment by ffleader1** [comment]
So any news on this?

**Comment by DeadSix27** [comment]
@ffleader1 ?? Waiting for a stacktrace (debug log) from you

**Comment by ffleader1** [comment]
wait whut .-.
I thought... nvm
So I got VS 2015. How do I do it.

**Comment by DeadSix27** [comment]
@ffleader1 https://msdn.microsoft.com/de-de/library/sc65sadd.aspx

**Comment by ffleader1** [comment]
Okay so maybe it's better for you to do Teamviewer to be honest, if you don't mind, but maybe tomorrow because it's like 3.04 AM here.

**Comment by ffleader1** [comment]
Oh hi, just want you to know that V5.2 is no longer crashing, I don't know it's either that or because I bought a new GPU, the AMD Rx 560.

Now the Rx 560 will crash with the GUI Koroshell, but run fines with yours, so I guess that is that. Thank you.

**Comment by ffleader1** [comment]
Okay you know what, I think I know what is the problem. I put the release (V5.2) in drive C, and set the environment variable to that folder. However, when typing the command, it says it cannot your model_rgb/noise1_model.json file.
![image](https://user-images.githubusercontent.com/15016720/36059279-ac2c8812-0e67-11e8-890d-94bccfa721a6.png)
That should be the cause. However, if I but the folder mode_rgb in the same place as where I run the command prompt, then it will work, even though I use the executable from another location.
(Like in the image, the executable is waifu2x-converter-cpp.exe in my drive K, while I am using the renamed waifu2x.exe in my Drive C)
![image](https://user-images.githubusercontent.com/15016720/36059303-496b53d8-0e68-11e8-9d63-592d500bff9f.png)
So, yeah, I guess that is the problem.

**Comment by YukihoAA** [comment]
I don't think waifu2x converter have to support this special case.... 

It has quite simple solution when it use Win32API.

Set CurrentDirectory to location of waifu2x-converter-cpp.exe will solve this issue but it can cause dependence problem. (may not support in linux and mac)

**Comment by YukihoAA** [comment]
also, I recommend Snowshell(https://github.com/YukihoAA/waifu2x_snowshell) to use instead of koroshell.

**Comment by ffleader1** [comment]
I mean... I just want to report a problem, that is all. Also, thank for the snowshell XD
