### ISSUE TITLE
-o option automatically append .png to the output filename

### ISSUE THREAD

**Issue by Q3CPMA** [DeadSix27/waifu2x-converter-cpp#49]
Hello,

title says it all. Should only do it on automatic mode.

**Comment by YukihoAA** [comment]
Hi, @Q3CPMA.
This Problem will only occurs in Windows because It use" \\" to express directory instead of "/".
I will make pull request for this problem in a minute.

**Comment by DeadSix27** [comment]
@YukihoAA Thanks :) I have not yet looked into this issue.

**Comment by Q3CPMA** [comment]
I'm not on Windows, though (Gentoo GNU/Linux).

**Comment by DeadSix27** [comment]
@Q3CPMA Is it fixed by the same PR? Or does the issue still exist.

**Comment by Q3CPMA** [comment]
Looks like it works.
