### ISSUE TITLE
Performace issue

### ISSUE THREAD

**Issue by FluffyDiscord** [DeadSix27/waifu2x-converter-cpp#5]
hi, I have tested your latest windows binary and latest wl-amigo's windows binary using one picture.
Your version's performace was around 148GFLOPS (on my rx 470) and wl-amigo's version was around 232GFLOPS.
How so your build is slower by a lot even when you are using latest opencv library?

**Comment by DeadSix27** [comment]
Not sure, I changed nothing special other than the opencv version and the bin check, maybe the precompiled opencv library offered by them is not that good performing anymore?

**Comment by max20091** [comment]
I don't see anything different between tanakamura OpenCL version and DeadSix27 OpenCL version  
I have a few question:  
Did you have OpenCL in your computer?  
Did you force the converter use your GPU instead of CPU? (Since newer gen CPU also have OpenCL)  
did you facing the downclock glitch on your GPU? https://www.reddit.com/r/Amd/comments/5pg1vp/i_also_have_the_300_mhz_mem_clock_glitch_but_on/  
It really weird that my GPU is much weaker than your but I have 300GFLOPS, my GPU is HD 7730

**Comment by FluffyDiscord** [comment]
Weird indeed.
I have AMD APP SDK v3.0 installed
It is definitely using my gpu - at the start I can see OpenCL: Ellesmere (thats rx 470)
I am not sure forcing will help when it is already using my GPU
I do not experience such a glitch, also I am aware of downsides of Hynix memory timings. (msi rx 470 4gb)

Am I missing something?

**Comment by DeadSix27** [comment]
@FluffyDiscord 
Download the https://github.com/logos Octocat logo then use the JPEG!
And run the following using my latest w2x binary.


Find GPU: (which in my case is for sure Number 0)
```
G:\w2x\40>waifu2x-converter-cpp.exe --list-processor
   0: Hawaii                                       (OpenCL    ): num_core=44
   1: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz     (FMA       ): num_core=8
   2: Intel(R) HD Graphics 530                     (OpenCL    ): num_core=24
   3: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz     (OpenCL    ): num_core=8
   4: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz     (OpenCL    ): num_core=8
```
Then run:
```
G:\w2x\40>waifu2x-converter-cpp.exe -i Octocat.jpg --processor 0
OpenCL: Hawaii
start process block (0,0) ...
......
process successfully done! (all:2.16128[sec], 763.748[GFLOPS], filter:1.88994[sec], 873.402[GFLOPS])
```


I then ran the same thing on tanakamura version:
```
G:\w2x\40\tanaka>waifu2x-converter_x64.exe -i Octocat.jpg --processor 0
OpenCL: Hawaii
process successfully done! (all:3.30762[sec], 499.052[GFLOPS], filter:1.89739[sec], 869.972[GFLOPS])
```

In which case mine is actually faster.

**Comment by FluffyDiscord** [comment]
Tried your method, results are here
---------
deadsix27, first try (I do not get this one)
![deadsix27_1](https://cloud.githubusercontent.com/assets/10332247/22334626/c002311e-e3db-11e6-917f-aaf0f4a3c8ae.jpg)
deadsix27, second try
![deadsix27_2](https://cloud.githubusercontent.com/assets/10332247/22334628/c007cf34-e3db-11e6-9868-c3b2e95f667e.jpg)
---------
tanakamura, first try
![tanakamura_1](https://cloud.githubusercontent.com/assets/10332247/22334625/c00054b6-e3db-11e6-880e-7c9177ddbc4c.jpg)
tanakamura, second try
![tanakamura_2](https://cloud.githubusercontent.com/assets/10332247/22334627/c005b03c-e3db-11e6-826b-eff338ff8d93.jpg)
---------
I see some weird performace drop from the start.
Scores are even with that second try.
So, no performace boost with some random "farts" now and then.

**Comment by DeadSix27** [comment]
@FluffyDiscord the random performance dips can be anything, you doing something on your pc, your windows install doing something and so on. plus this software isn't flawless.

**Comment by FluffyDiscord** [comment]
Alrigthy

**Comment by GiRaFa-SM** [comment]
Here I have about 930 gflops performance sometimes. R9 280

**Comment by max20091** [comment]
Codes from tanakamura fork are very outdated and not efficient for OpenCL computing 
From the old benchmark, tanakamura only have 291GFLOPS while full performance is about 800 GFLOPS
I only have 300 GFLOPS while full performance is about 600 GFLOPS

**Comment by FluffyDiscord** [comment]
@GiRaFa-SM The smaller the picture is, the higher your GFLOPS value will be =] Try to upscale some 4K picture and you will see that you get a lot less.

**Comment by GiRaFa-SM** [comment]
https://youtu.be/MBroPU2PGmg

600Gflops upscaling an 4k image using your waifu2x cmd+koroshell exe.
