### ISSUE TITLE
Ignoring tags in file name while batch processing

### ISSUE THREAD

**Issue by iZN1337** [DeadSix27/waifu2x-converter-cpp#56]
It's a small request since it'd save a lot of time in batch processing many images. If there's a chance of disabling the tags that are added once the files are generated so that the file name remains same as the original.

## Example:

**File name is:** 0004.png
**Output is turning into:** 0004_[NS-L3][x2.000000].png
**While it should be:** 0004.png

Thanks!

**Comment by Tsutsukakushi** [comment]
Have you considered just using make and explicitly giving the output filename with -o?
