### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by Aidolii** [DeadSix27/waifu2x-converter-cpp#59]
Why do you have a Discord invite on your page where you can't view message history and then kick anyone who asks a question?

**Comment by DeadSix27** [comment]
@Aidolii Probably pissed someone off? Also this is a issue tracker for w2x, not for my discord.

**Comment by Aidolii** [comment]
>@Aidolii Probably pissed someone off? Also this is a issue tracker for w2x, not for my discord.

I asked two serious questions and then one silly question as friendly banter and that apparently pissed someone off?

**Comment by DeadSix27** [comment]
Probably? What are your questions?

**Comment by Aidolii** [comment]
So I came in, and I said something along the lines of

@DeadSix27 I can't view message history? I guess I'm going to have to ask questions that may have already been answered? Like, is the AMD SDK required for people who just want to use CUDA? Has someone already done that and uploaded it somewhere?

Then I figured you might be afk and I saw you and the admin were in a question about Rainbow Six, and I pinged then and asked 'Do you think love can bloom on the battlefield?' hoping they would find that funny and answer my serious questions. I was immediately kickbanned.

**Comment by DeadSix27** [comment]
@Aidolii What is your operating system and no, not on Linux and Windows, you can compile with both or with only one of them.
And if you use the windows binary, only OpenCL works atm, I will add a cuda and amd one later. 

About the game question, I asked the person and he thought you were a spammer first, 'cuz generally people dislike being randomly mentioned midgame.

**Comment by Aidolii** [comment]
>About the game question, I asked the person and he thought you were a spammer first, 'cuz generally people dislike being randomly mentioned midgame.

It wasn't random, I had serious questions and I was hoping that someone with administrative access could open up message history so I didn't have to bother anyone. IMMEDIATELY banned. I was taken aback. Can you please unban me so we can talk on Discord and not on a github issue?

**Comment by DeadSix27** [comment]
@Aidolii That question was actually never asked before, but ye, It's not really a dev discord, but more like a private one.

**Comment by Aidolii** [comment]
Your front page says: "It's often easier to chat in real time, so if you want feel free to join."

So that's what I did? And could you unban me because I agree with the sentiment that it's easier to chat in real time.

**Comment by DeadSix27** [comment]
@Aidolii Have fun. Stick waifu2x questions in #waifu2x though.
