### ISSUE TITLE
I just found a way to use Waifu2X and set custom paramethers through a GUI interface.

### ISSUE THREAD

**Issue by GiRaFa-SM** [DeadSix27/waifu2x-converter-cpp#6]
I used Waifu2X Koroshell (CPU Ver.) files to do this. You just need to drag your pic in the Waifu2X window and they'll convert using comand line.
I renamed "waifu2x-converter-cpp.exe" to "waifu2x-converter_x64.exe" to make koroshell exe recognize this file and upscale. Here's the link of the file. 

https://drive.google.com/file/d/0B1VV-pX3WjWLTmRMV0hfLTg1Vzg/view?usp=sharing

Cant you guys fork this .exe(waifu2x-x64.exe) too? On windows 10 i'm having some issues, and or/also make the batch script CMD window minimized while doing the process, having a window popping-out everytime is too annoying.

**Comment by max20091** [comment]
this is the batch CMD version for this fork: https://github.com/max20091/Waifu2x-converter-CMD-GUI

**Comment by GiRaFa-SM** [comment]
Maybe you misunderstood? Or I wasn't clear? 
What I said on the first message was:

I downloaded your forked Waifu2x 
I downloaded Waifu2x Koroshell 
I renamed the file converter-cpp to converter-x64 to make waifu2x Koroshell exe recognize this file as the batch CMD file. I paste all files from your fork into waifu2x-converter folder(Koroshell folder) This way, I can customize parameters through a graphical interface, if compared with your current solution, and still using the new and fixed features on this fork. 

My question is, is it possible to you implement or add the koroshell app to your fork? It has some issues on windows 10, and when I try to convert multiple images the CMD batch window keeps popping out everytime. 

Download the file above and test by yourself, please.

**Comment by DeadSix27** [comment]
What exactly do you want? A GUI?

**Comment by GiRaFa-SM** [comment]
Sigh, i recorded a video, it's easier to explain this way.
https://youtu.be/7LlCwn_OtfU

**Comment by DeadSix27** [comment]
So let me sum up what you "found out" and what you "want", you just noticed that the original waifu2x-cpp uses the same parameters and thus works with that 1 GUI, which is not surprising and  what you want is a GUI, so in short, issue solved?

**Comment by GiRaFa-SM** [comment]
The original waifu2x use CPU to process the files, your waifu2x uses GPU. 
Doing what I did on the video allows you to process files using a gui and the possibility of customizing parameters. 

I want to know if you guys can fork and improve waifu2x koroshell exe (because it has some issues on windows 10 (probably you noticed on my video). And tbh, it's much more practical doing this through waifu2x koroshell exe. 

Sorry for not being clear.

**Comment by max20091** [comment]
Just grab my version I said above, waifu2x koroshell isn't open-source so I make a GUI myself from scratch.
It have most features from koroshell as well as fixed most of bugs.

**Comment by GiRaFa-SM** [comment]
I'm already doing this, i'm using your version and using koroshell's gui to set specific parameters while upscaling something.
Sorry if this sound stupid, but do you have any ETA?

**Comment by max20091** [comment]
Soon, maybe today I will release my next version with block size added
