### ISSUE TITLE
VS2017 + CUDA 9.1 compilation bug that affects this project

### ISSUE THREAD

**Issue by Aidolii** [DeadSix27/waifu2x-converter-cpp#60]
When you use CUDA 9.1 and VS2017 together to compile, you need to have the 'VS++ 2017 version 15.4 v14.11 toolset' component from the Visual Studio Installer, and a line in a CUDA header file which doesn't allow you to use said version needs to be changed.

Open ``C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\include\crt\host_config.h``
Find ``#if _MSC_VER < 1600 || _MSC_VER > 1911``, should be line 133.
Change 1911 to 1912 (or any number higher than 1911 really, since it's just a check).

After that, it should compile fine.

Credit: @DeadSix27

**Comment by YukihoAA** [comment]
NVIDIA doesn't recommend to use latest version of VS 2017.

Please use VS2017 14.5 instead

[Download](https://docs.microsoft.com/ko-kr/visualstudio/productinfo/installing-an-earlier-release-of-vs2017)

NVIDIA forum: https://devtalk.nvidia.com/default/topic/1027299/cuda-setup-and-installation/cuda-9-failed-to-support-the-latest-visual-studio-2017-version-15-5/post/5225630/#5225630

**Comment by DeadSix27** [comment]
@YukihoAA He added the issue after I told him how I build it on Windows.

The work around works fine, so I see no problem with it as long hes fine with editing a cuda header.

**Comment by DeadSix27** [comment]
Updated the build guide accordingly: https://github.com/DeadSix27/waifu2x-converter-cpp/blob/master/BUILDING.md
