### ISSUE TITLE
No CPU multithreading

### ISSUE THREAD

**Issue by Saren-Arterius** [DeadSix27/waifu2x-converter-cpp#62]
tanakamura's version (I ran the prebuilt binary-form release in wine) can use all my CPU threads, while this fork seems to use only single CPU core.

**Comment by Saren-Arterius** [comment]
tanakamura's version in wine's `--list-processor`
```
[saren@Saren-Workstation /tmp/waifu2x-converter_x64_1130 ]% /usr/bin/wine waifu2x-converter_x64.exe --list-processor
   0: GeForce GTX 660 Ti                           (OpenCL    ): num_core=7
   1: Intel(R) Xeon(R) CPU E5-2696 v3 @ 2.30GHz    (FMA       ): num_core=64
```
This fork's `--list-processor`
```
[saren@Saren-Workstation /tmp/waifu2x-converter_x64_1130 ]% waifu2x-converter-cpp --list-processor
   0: GeForce GTX 660 Ti                           (CUDA      ): num_core=7
   1: GeForce GTX 660 Ti                           (OpenCL    ): num_core=7
   2: Intel(R) Xeon(R) CPU E5-2696 v3 @ 2.30GHz    (FMA       ): num_core=72
```

**Comment by DeadSix27** [comment]
Works fine for me:
![image](https://user-images.githubusercontent.com/1492505/38470558-e2a99edc-3b64-11e8-8367-5182d42875ff.png)

**Comment by Saren-Arterius** [comment]
@DeadSix27 I am on `waifu2x-converter-cpp-git r572.1522558468.0529f44-1`, Arch Linux.

**Comment by DeadSix27** [comment]
@Saren-Arterius Works for me on arch too:
![image](https://user-images.githubusercontent.com/1492505/38470587-61ce00a4-3b65-11e8-9019-ce4d5e2fdd36.png)

**Comment by DeadSix27** [comment]
Also, why are you running it on wine? Can't you just compile it natively?

**Comment by Saren-Arterius** [comment]
@DeadSix27 I see. I just tested this fork's windows binary using wine, and it seems that multithreading works fine (but `bad allocation` is shown due to wine's problems). I run tanakamura's version on wine because it can no longer be complied natively. It seems that I need to investigate this issue since it's only just me...

What's your `--list-processor`?

**Comment by DeadSix27** [comment]
@Saren-Arterius 
on my arch box: 
   0: Intel(R) HD Graphics Kabylake Desktop GT2    (OpenCL    ): num_core=23
   1: Intel(R) Pentium(R) CPU G4620 @ 3.70GHz      (SSE3      ): num_core=4
on my windows desktop:
   0: AMD R9 390x                                      (OpenCL    ): num_core=44
   1: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz     (FMA       ): num_core=8
   2: Intel(R) HD Graphics 530                     (OpenCL    ): num_core=24
   3: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz     (OpenCL    ): num_core=8
   4: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz     (OpenCL    ): num_core=8

**Comment by DeadSix27** [comment]
I just remembered that the arch box has no FMA, maybe FMA multi threading is bugged on linux? I can't test that though as I have no linux pc with FMA capable CPU.

**Comment by Saren-Arterius** [comment]
I observed a weird behavior. If I disabled most of the CPUs by writing `0` to `/sys/devices/system/cpu/cpu${i}/online`, and then I run `waifu2x-converter-cpp` with same settings, meanwhile I re-enable the CPUs, it will sudden speed up and use more cores. I suppose `waifu2x-converter-cpp` does not like a NUMA system?

**Comment by DeadSix27** [comment]
@Saren-Arterius build and run:

```cpp
#include <iostream>
#include <thread>
 
int main() {
    unsigned int n = std::thread::hardware_concurrency();
    std::cout << n << " concurrent threads are supported.\n";
}
```
```bash
$ gcc -lstdc++ test.cpp -o test
```
```
$ ./test
4 concurrent threads are supported.
```

See if the correct number is displayed?

**Comment by DeadSix27** [comment]
PS: you can manually define threads with -j btw, set it to num of cores and check again?

**Comment by Saren-Arterius** [comment]
`72 concurrent threads are supported.`

`-j 72` does not work for me.

**Comment by DeadSix27** [comment]
"does not work for me" any error? what did you observe?

**Comment by DeadSix27** [comment]
strange, can you verify it runs on X amount of threads then? 
I think htop can show threads for processes? Idk something similar to PH in windows:
![image](https://user-images.githubusercontent.com/1492505/38500366-823acb06-3c0a-11e8-894c-eae2a749a3a3.png)
Just run it with -j 100 or so, if it wont use at least 100.. then there is something wrong with the program.. otherwise I have no clue whats up.. because shouldn't the Operating system manage threads across cores?

**Comment by Saren-Arterius** [comment]
![image](https://user-images.githubusercontent.com/4948919/38500468-11eb483e-3c3d-11e8-83bb-41d2bf6afbc5.png)

**Comment by DeadSix27** [comment]
@Saren-Arterius check the actual thread count, not your system usage.

**Comment by DeadSix27** [comment]
`ps huH p <PID of w2x> | wc -l`

**Comment by Saren-Arterius** [comment]
@DeadSix27 `217`, htop shows a lot of userland threads also.

**Comment by Saren-Arterius** [comment]
![image](https://user-images.githubusercontent.com/4948919/38500594-7ad7f932-3c3d-11e8-9a64-4f7a99c34856.png)

**Comment by DeadSix27** [comment]
is 217  the output of the command line i told you to run?

**Comment by Saren-Arterius** [comment]
@DeadSix27 yes.

**Comment by DeadSix27** [comment]
Thats a lot of threads, but still, there seems to be another issue than multi threading.. it does multi thread.. just doesn't fully utilize the cpu.. that cpu  has SSE and FMA right?
And you are using a processor of the list that shows up with FMA right?
`1: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz     (FMA       ): num_core=8`

**Comment by Saren-Arterius** [comment]
@DeadSix27 
`2: Intel(R) Xeon(R) CPU E5-2696 v3 @ 2.30GHz    (FMA       ): num_core=72`
and the command I used `waifu2x-converter-cpp -j 144 -p 2 --block_size 2048 -i ~/圖片/16475993_p1_master1200_\[NS-L1\]\[x4.000000\].png`

**Comment by DeadSix27** [comment]
:/ Then I have no idea.., does using the cpu with OpenCL utilize the whole cpu then?

**Comment by Saren-Arterius** [comment]
@DeadSix27 I tested opencl with `pocl` as implementation, it does not use all core and the performance is even lower.

**Comment by DeadSix27** [comment]
Sorry I couldn't help maybe one of the main coders that helped me out can help here..

**Comment by YukihoAA** [comment]
Maybe this issue refers to 

[ModelHandler.cpp]
https://github.com/DeadSix27/waifu2x-converter-cpp/blob/1dfdb1e4e952f335343b10548e97b4cd6993d8cc/src/modelHandler.cpp#L65

**Comment by Saren-Arterius** [comment]
It is no longer an issue for me but I can't reproduce or finding this cause for this issue.
