### ISSUE TITLE
Add noise reduction level 0 support

### ISSUE THREAD

**Issue by f11894** [DeadSix27/waifu2x-converter-cpp#63]
Although it is named level 0, it does not mean that it does not perform noise reduction.
In fact, the noise reduction is performed slightly.

**Comment by YukihoAA** [comment]
I'm working on this issue.

I'll create PR in few days

**Comment by DeadSix27** [comment]
Added via https://github.com/DeadSix27/waifu2x-converter-cpp/pull/76 see https://github.com/DeadSix27/waifu2x-converter-cpp/releases/tag/v5.2.2 for Windows build
