### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by Mutuerz** [DeadSix27/waifu2x-converter-cpp#65]
Sorry for bothering, I just cant figure out how to use this, I have nvidia, so I know I have to do something extra, but besides that I don't how it should work or what to do to make it work, so a brief explanation will be greatly appreaciated, I will buy you a coffee

**Comment by DeadSix27** [comment]
For linux or Windows ?

**Comment by Mutuerz** [comment]
Hi, srry for the late answer, Windows 10
