### ISSUE TITLE
Ubuntu compile fails: "This file [...] support for the ISO C++ 2011 standard."

### ISSUE THREAD

**Issue by brunoais** [DeadSix27/waifu2x-converter-cpp#69]
First error (probably the most relevant) that appears (it is many KB long):
```
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support
```
cmake version 3.13.0
g++ version: 5.4.0
uname -a: Linux PC 4.15.0-39-generic #42~16.04.1-Ubuntu SMP Wed Oct 24 12:09:54 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

I'm trying to compile the current master version to use waifu2x for myself.
I already tried to check the generated make files and everything appears to be correct (although the generated content is huge).
Any idea what I may be doing wrong?
I'm following [these instructions](https://github.com/DeadSix27/waifu2x-converter-cpp/blob/master/BUILDING.md#linux)

**Comment by YukihoAA** [comment]
@brunoais 
I changed CMakeLists.txt to support GCC 5.
May be It helps you
