### ISSUE TITLE
How do I use it?

### ISSUE THREAD

**Issue by Martinquestion** [DeadSix27/waifu2x-converter-cpp#72]
I have windows 7, I just downloaded this but I do not know how to use it? Can anyone give me instructions.

**Comment by YukihoAA** [comment]
Usage of this program can be seen by executing `waifu2x-converter-cpp --help` in cmd.exe

If you are not use to CUI Application you may consider about using my GUI application[waifu2x-snowshell](https://github.com/YukihoAA/waifu2x_snowshell).

**Comment by DeadSix27** [comment]
@Martinquestion If you have further questions reply, I'll close this for now as it's answered by @YukihoAA
