### ISSUE TITLE
AMD APP SDK V3.0 Installer Download Link Currently Unavailable

### ISSUE THREAD

**Issue by YukihoAA** [DeadSix27/waifu2x-converter-cpp#74]
Installer links in BUILDING.md is currently dead, so I found some other links.

If you have the original installer file downloaded from the AMD / AMD forum, compare the checksum of each file and please reply on this thread whether these files are same or not.

You can get checksum easily by using [HashTab](http://implbits.com/products/hashtab/)

YourUpload - [AMD-APP-SDKInstaller-v3.0.130.135-GA-windows-F-x64](https://www.yourupload.com/view/1824157) 
Softpedia - [AMD Accelerated Parallel Processing SDK](https://www.softpedia.com/get/Programming/SDK-DDK/ATI-Stream-SDK.shtml)

`SHA-1: 02B38B540E565BE177BA8EA248C56B6CC70D3200`

**Comment by DeadSix27** [comment]
another mirror: https://mega.nz/#!cuABBIrT!hsUr5JBF7YJats7z_dDRTHrOxrIERkcy79d-iR8XkEM
```
>powershell Get-FileHash "AMD-APP-SDKInstaller-v3.0.130.135-GA-windows-F-x64.exe"

Algorithm       Hash
---------       ----
SHA256          360B054AFCD3B926FCF22CB208D9BCA87F27B17AE4753EC0E4E7BCDC871C841C
SHA1            02B38B540E565BE177BA8EA248C56B6CC70D3200
```

**Comment by YukihoAA** [comment]
thank you very much!
