### ISSUE TITLE
Add issue template and basic how to use guide

### ISSUE THREAD

**Issue by DeadSix27** [DeadSix27/waifu2x-converter-cpp#84]
(Issue mostly a reminder for myself)

I need to add a basic guide explaining it's a command line application (and link to guides on how to open said command line and some basic usage info)

It would also be nice to link to known working GUI's and Batch Scripts etc.
@YukihoAA You made a GUI right? Post the URL please so I know it :)
PS: Who is laclia's GUI.. 

![image](https://user-images.githubusercontent.com/1492505/50465859-53f9bc80-099a-11e9-965c-9e21784e96b5.png)

**Comment by YukihoAA** [comment]
My GUI Project: [waifu2x_snowshell](https://github.com/YukihoAA/waifu2x_snowshell)
