### ISSUE TITLE
Clean up cmake regarding nvidia/amd cl detection

### ISSUE THREAD

**Issue by DeadSix27** [DeadSix27/waifu2x-converter-cpp#96]
I used a work around back then to force using a specific opencl header but I don't think that's necessary, I need to remove that or simplify it.

- CUDA also has to be made optional and not auto detected and applied. (e.g make it a manual option in cmake)

- unify options to "WITH" or "ENABLE"
e.g ENABLE_CUDA, ENABLE_UNICODE or WITH_CUD.., WITH_UN...

- Finally add a simple summary at end of cmake to summarize the aforementioned options and their status

**Comment by DeadSix27** [comment]
@YukihoAA You have a AMD Card right? I'll send you a few cmake patches at some point so you can see if it runs fine on both nvidia and amd. (Do you happen to have an AMD Ryzen APU too? (Also, is your amd dGPU a vega?))

**Comment by YukihoAA** [comment]
@DeadSix27 

I used R9 280X until 18.12.30 and It dead in 12.31, RIP 280X..

I'm using Ryzen 5 2700X & RX590 now. but 2700X does not have APU inside. 

:(
